import type { Lesson } from "../types";

/**
 * Seed lesson catalog. Each object is pure content — adding a lesson
 * never requires touching a component. See §37 of the brief.
 */
export const lessons: Lesson[] = [
  {
    id: "ethernet-switching",
    title: "Ethernet & Switching",
    tagline: "How frames find their way across a LAN, one MAC address at a time.",
    category: "fundamentals",
    difficulty: "beginner",
    prerequisites: [],
    estimatedMinutes: 15,
    tier: "free",
    sections: [
      { id: "problem", heading: "The problem", body: "Two hosts on the same wire need to reach each other, but IP means nothing to a switch — it only sees frames." },
      { id: "solution", heading: "How switching solves it", body: "Switches learn source MAC addresses per port and build a CAM table, forwarding unicast frames only where they need to go and flooding the unknown." },
    ],
  },
  {
    id: "arp-resolution",
    title: "ARP: Resolving IP to MAC",
    tagline: "Watch a broadcast question get exactly one answer.",
    category: "fundamentals",
    difficulty: "beginner",
    prerequisites: ["ethernet-switching"],
    estimatedMinutes: 10,
    simulationPath: "/demo/first-connection",
    tier: "free",
    sections: [
      { id: "problem", heading: "The problem", body: "Your PC knows the gateway's IP address, but Ethernet frames are addressed with MAC addresses, not IPs." },
      { id: "solution", heading: "How ARP solves it", body: "ARP broadcasts \"who has this IP?\" — only the owner replies, unicast, and the answer is cached." },
    ],
  },
  {
    id: "tcp-three-way-handshake",
    title: "TCP Three-Way Handshake",
    tagline: "SYN, SYN-ACK, ACK — and why the order matters.",
    category: "fundamentals",
    difficulty: "beginner",
    prerequisites: ["ipv4-basics"],
    estimatedMinutes: 12,
    simulationPath: "/demo/first-connection",
    tier: "free",
    sections: [
      { id: "problem", heading: "The problem", body: "IP alone gives no guarantee packets arrive, arrive once, or arrive in order." },
      { id: "solution", heading: "How TCP solves it", body: "Both sides exchange initial sequence numbers and acknowledge them before any data is trusted to have arrived." },
    ],
  },
  {
    id: "ipv4-basics",
    title: "IPv4 Addressing & Subnetting",
    tagline: "Carving one address space into networks that route cleanly.",
    category: "fundamentals",
    difficulty: "beginner",
    prerequisites: [],
    estimatedMinutes: 20,
    tier: "free",
    sections: [
      { id: "problem", heading: "The problem", body: "Every host can't be its own broadcast domain — networks need to be grouped and routed between." },
      { id: "solution", heading: "How subnetting solves it", body: "A mask splits an address into network and host portions, letting routers make forwarding decisions on prefixes instead of individual hosts." },
    ],
  },
  {
    id: "vlan-fundamentals",
    title: "VLANs & Trunking",
    tagline: "One switch, many broadcast domains.",
    category: "enterprise",
    difficulty: "associate",
    prerequisites: ["ethernet-switching"],
    estimatedMinutes: 18,
    tier: "free",
    sections: [
      { id: "problem", heading: "The problem", body: "Every device in one broadcast domain sees every broadcast — that doesn't scale, and it doesn't separate departments." },
      { id: "solution", heading: "How VLANs solve it", body: "A VLAN tag (802.1Q) lets one physical switch (and one trunk) carry many logically isolated broadcast domains." },
    ],
  },
  {
    id: "ospf-fundamentals",
    title: "OSPF: Link-State Routing",
    tagline: "How R1 learns about a network three hops away, automatically.",
    category: "enterprise",
    difficulty: "professional",
    prerequisites: ["ipv4-basics"],
    estimatedMinutes: 25,
    simulationPath: "/demo/ospf-area0",
    tier: "free",
    sections: [
      { id: "problem", heading: "The problem", body: "R1 only knows its directly connected networks. How does it learn what's behind R2, without an administrator typing every route by hand?" },
      { id: "solution", heading: "How OSPF solves it", body: "Routers flood link-state advertisements, build an identical topology database, and each independently runs Dijkstra's SPF algorithm." },
    ],
  },
  {
    id: "bgp-fundamentals",
    title: "BGP: Path Selection Between Networks",
    tagline: "The protocol that glues autonomous systems into the Internet.",
    category: "service-provider",
    difficulty: "professional",
    prerequisites: ["ospf-fundamentals"],
    estimatedMinutes: 30,
    simulationPath: "/demo/bgp-enterprise",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Two organizations, each running their own IGP, need to exchange reachability without trusting each other's internal routing." },
      { id: "solution", heading: "How BGP solves it", body: "BGP exchanges prefixes tagged with policy attributes (AS_PATH, LOCAL_PREF, MED) and applies a deterministic best-path algorithm." },
    ],
  },
  {
    id: "mpls-fundamentals",
    title: "MPLS: Label Switching",
    tagline: "Push, swap, pop — forwarding by label instead of by lookup.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["bgp-fundamentals"],
    estimatedMinutes: 30,
    simulationPath: "/demo/mpls-ldp",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A provider core wants to classify traffic once, at the edge, and layer scalable services and traffic engineering on top — not just repeat an IP lookup at every hop." },
      { id: "solution", heading: "How MPLS solves it", body: "An ingress LER pushes a short label once; every P router in the core swaps it using only that label — never a customer IP lookup — until the egress LER exposes the original packet again." },
    ],
  },
  {
    id: "mpls-l3vpn",
    title: "MPLS L3VPN",
    tagline: "VRF + Route Distinguisher + Route Target + MP-BGP — private routing over a shared core.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-fundamentals"],
    estimatedMinutes: 35,
    simulationPath: "/demo/mpls-l3vpn",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A provider core carries hundreds of customers. It can't hold every customer's IPv4 routes — but each customer still needs private, isolated Layer-3 connectivity between their own sites." },
      { id: "solution", heading: "How L3VPN solves it", body: "A VRF per customer per PE keeps routing separated; MP-BGP carries VPNv4 routes (RD for uniqueness, RT for import/export policy, plus a VPN label) between PEs; the existing MPLS transport LSP carries the labeled packet, with the P routers in the core never touching a customer route at all." },
    ],
  },
  {
    id: "mpls-rsvp-te",
    title: "MPLS RSVP-TE",
    tagline: "CSPF, PATH/RESV signaling, and bandwidth-reserved, traffic-engineered LSPs.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-l3vpn"],
    estimatedMinutes: 40,
    simulationPath: "/demo/mpls-rsvp-te",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "The IGP's shortest path is sometimes a path that can never satisfy a bandwidth requirement — a link's maximum reservable bandwidth is a hard TE ceiling, not a measure of momentary congestion." },
      { id: "solution", heading: "How RSVP-TE solves it", body: "Constrained Shortest Path First (CSPF) prunes every link that violates a constraint from the Traffic Engineering Database before computing a path at all. RSVP-TE then signals that constrained path — PATH downstream, RESV upstream — installing downstream-assigned labels and reserving real bandwidth hop by hop, so MPLS traffic follows the engineered path instead of the IGP shortest path." },
    ],
  },
  {
    id: "mpls-rsvp-frr",
    title: "MPLS RSVP-TE Fast Reroute",
    tagline: "Local repair, PLR, Merge Point, and pre-built bypass tunnels — link and node protection.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-rsvp-te"],
    estimatedMinutes: 40,
    simulationPath: "/demo/mpls-rsvp-frr",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "When a link or transit router on an active RSVP-TE LSP fails, waiting for the headend to detect the failure, recompute CSPF, and re-signal an entire new end-to-end LSP is too slow for traffic that can't tolerate the interruption." },
      { id: "solution", heading: "How Fast Reroute solves it", body: "A Point of Local Repair (PLR) sits right next to the protected resource with a bypass tunnel already signaled, labeled, and reserved before any failure occurs. On local link/interface-down detection, the PLR activates that bypass in an instant — pushing an outer bypass label on top of the protected LSP's own inner label — without waiting for the headend. A Merge Point rejoins the bypass to the ordinary protected LSP, which resumes completely normal forwarding. The headend may still reoptimize a new end-to-end path later, but FRR itself is local, not global." },
    ],
  },
  {
    id: "sr-mpls-foundations",
    title: "SR-MPLS Foundations",
    tagline: "Node SID, Prefix-SID, Adjacency SID, SRGB, and segment stacks — steering without RSVP.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-rsvp-frr"],
    estimatedMinutes: 45,
    simulationPath: "/demo/sr-mpls-foundations",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "RSVP-TE engineers a path by signaling PATH/RESV hop by hop and maintaining per-LSP state along the way. Can traffic be steered with a short list of instructions instead — without signaling an end-to-end LSP for every path?" },
      { id: "solution", heading: "How SR-MPLS solves it", body: "The IGP distributes Segment Routing information alongside ordinary topology — a Node SID means \"reach this router via the shortest path,\" an Adjacency SID means \"use this one specific link, but only at the router that owns it.\" The headend imposes an ordered MPLS label stack once; each router along the way executes whichever segment is currently active, without recomputing anything end to end." },
    ],
  },
  {
    id: "sr-policy",
    title: "SR Traffic Engineering / SR Policy",
    tagline: "Color, endpoint, candidate paths, segment lists, BSID, and traffic steering — turning SIDs into intent.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["sr-mpls-foundations"],
    estimatedMinutes: 50,
    simulationPath: "/demo/sr-policy",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "SR-MPLS Foundations showed how individual SIDs work. But an operator rarely wants \"one segment list\" — they want intent that survives topology change: GOLD traffic toward R6 must use a specific engineered path, with a defined fallback if that path stops working, distinct from ordinary IGP reachability." },
      { id: "solution", heading: "How SR Policy solves it", body: "An SR Policy is identified by <Headend, Color, Endpoint> — not a label stack. It holds one or more candidate paths — an explicit, operator-specified segment list and/or a dynamic one computed from TE constraints — and the highest-preference VALID candidate becomes active, resolving a Binding SID and a real segment list. Traffic must still be explicitly steered into the policy; an UP policy does not itself redirect every packet toward its endpoint." },
    ],
  },
  {
    id: "sr-ti-lfa",
    title: "SR-MPLS TI-LFA",
    tagline: "P-Space, Q-Space, PQ nodes, repair lists, and local fast reroute — SR's answer to RSVP-TE FRR.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["sr-policy"],
    estimatedMinutes: 55,
    simulationPath: "/demo/sr-ti-lfa",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "SR Policy showed how to turn SIDs into steered intent, and RSVP-TE Fast Reroute showed local repair via a pre-signaled bypass LSP. Neither answers this: how can an SR router repair traffic locally after a failure — without waiting for the headend, and without pre-signaling anything?" },
      { id: "solution", heading: "How TI-LFA solves it", body: "Topology Independent Loop-Free Alternate precomputes, before any failure, a post-convergence SPF path, the PLR's own P-Space and the destination's Q-Space, a safe PQ repair point in their intersection, and a minimal SR repair segment list toward it. On local failure detection the PLR pushes that repair segment on top of the original SR instruction immediately — no signaling, no headend involvement, and the original segment resumes automatically once the repair point is reached." },
    ],
  },
  {
    id: "sr-flex-algo",
    title: "SR-MPLS Flex-Algo",
    tagline: "Algorithm-specific SPF, Flex-Algo Definitions, affinities, metrics, and algorithm-specific Prefix-SIDs.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["sr-ti-lfa"],
    estimatedMinutes: 55,
    simulationPath: "/demo/sr-flex-algo",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Normal Node-SID forwarding follows the IGP shortest path — Algorithm 0. But an operator sometimes wants the IGP itself to calculate an entirely different shortest-path topology, using different constraints, alongside the normal one — not a headend policy layered on top, a genuinely different distributed calculation." },
      { id: "solution", heading: "How Flex-Algo solves it", body: "A Flex-Algo Definition (FAD) — algorithm ID, metric type, and affinity constraints — is distributed via the IGP. Every participating router computes its OWN algorithm-specific SPF from it, and the same destination prefix gets a second, independently-derived Prefix-SID whose forwarding follows that algorithm's calculated topology instead of the default one. Link metrics or affinities can change the resulting path without ever changing the algorithm ID, and a router that stops participating is removed from that algorithm's topology entirely, not merely deprioritized." },
    ],
  },
  {
    id: "srv6-foundations",
    title: "SRv6 Foundations",
    tagline: "IPv6 SIDs, locators, functions, the Local SID Table, the SRH, and End processing — Segment Routing directly in the IPv6 data plane.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["sr-flex-algo"],
    estimatedMinutes: 55,
    simulationPath: "/demo/srv6-foundations",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "SR-MPLS steers traffic with a segment list imposed as an MPLS label stack — but that requires an MPLS data plane underneath. What happens when Segment Routing is instantiated directly in the IPv6 data plane instead of MPLS?" },
      { id: "solution", heading: "How SRv6 solves it", body: "A segment becomes a 128-bit IPv6 SID (LOC:FUNCT:ARG), routed to its owner by an ordinary locator prefix and bound to a behavior in that owner's Local SID Table. The active segment IS the IPv6 Destination Address; a Segment Routing Header carries the rest of the program — in reversed storage order — only when more than one segment is needed. The base End behavior decrements Segments Left and rewrites the DA — no MPLS label stack anywhere underneath." },
    ],
  },
  {
    id: "srv6-endpoint-behaviors",
    title: "SRv6 Endpoint Behaviors",
    tagline: "End, End.X, End.T, End.DX6/DX4, End.DT6/DT4, End.DX2 — the local instruction bound to a SID, not just the address that reaches it.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["srv6-foundations"],
    estimatedMinutes: 60,
    simulationPath: "/demo/srv6-endpoint-behaviors",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "SRv6 Foundations built one SID bound to one behavior — End. But if every SID is already routed to its owner by ordinary IPv6 forwarding, why does SRv6 define many different endpoint behaviors at all?" },
      { id: "solution", heading: "How endpoint behaviors solve it", body: "Reaching the node is only half the operation — the locally instantiated behavior bound to that exact SID decides what happens next. End.X forces forwarding through one bound adjacency instead of the ordinary FIB; End.T continues the program through a specific table; End.DX6/End.DX4/End.DT6/End.DT4/End.DX2 decapsulate the outer IPv6 header and cross-connect or table-route the exposed IPv6, IPv4, or Ethernet payload to a customer service — each a genuinely different forwarding decision, not a cosmetic label." },
    ],
  },
  {
    id: "srv6-policy",
    title: "SRv6 Traffic Engineering / SR Policy",
    tagline: "RFC 9256 candidate paths, validity, preference, H.Encaps, and a Binding SID — the layer that decides which SIDs traffic uses, not just what they do.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["srv6-endpoint-behaviors"],
    estimatedMinutes: 65,
    simulationPath: "/demo/srv6-policy",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "SRv6 Endpoint Behaviors taught what a SID does once traffic arrives. Ordinary IPv6 forwarding still only answers \"how do I reach R6?\" — it can't express \"reach R6 while satisfying a specific intent,\" like the lowest-delay path instead of the IGP-shortest one." },
      { id: "solution", heading: "How SR Policy solves it", body: "An SR Policy (RFC 9256) is identified by <Headend, Color, Endpoint>, carries one or more candidate paths (explicit or dynamically computed), and activates the highest-preference candidate that is actually VALID — never the other way around. The headend steers matching traffic onto it with H.Encaps, building a fresh outer IPv6 + SRH from whichever candidate is active, reusing the exact same End/End.X/End.DX6 endpoint-behavior processing already proven in the prior lesson." },
    ],
  },
  {
    id: "srv6-l3vpn",
    title: "SRv6 L3VPN",
    tagline: "RFC 9252 BGP Overlay Services — the same VRF/RD/RT/MP-BGP control plane, now advertising a real SRv6 Service SID instead of an MPLS VPN label.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["srv6-policy"],
    estimatedMinutes: 70,
    simulationPath: "/demo/srv6-l3vpn",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "MPLS L3VPN builds private Layer-3 connectivity with a VRF, an RD, a Route Target policy, MP-BGP, and a two-label MPLS stack. What happens to that whole model when the provider core stops running MPLS and forwards on plain IPv6/SRv6 instead?" },
      { id: "solution", heading: "How SRv6 L3VPN solves it", body: "VRF, RD, RT, and MP-BGP VPN routes all survive completely unchanged (RFC 4364). What changes is the egress service instruction: the BGP Prefix-SID Attribute's SRv6 L3 Service TLV (RFC 9252) carries a real SRv6 Service SID bound to a per-VRF End.DT4/End.DT6 behavior, resolved through that PE's own SRv6 locator — a dependency genuinely separate from ordinary BGP next-hop reachability." },
    ],
  },
  {
    id: "srv6-ti-lfa",
    title: "SRv6 Protection / TI-LFA",
    tagline: "RFC 9855 Topology Independent Fast Reroute — a precomputed outgoing interface plus a globally-routed End.X+USD repair SID, activated locally the instant a failure is detected.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["srv6-l3vpn"],
    estimatedMinutes: 75,
    simulationPath: "/demo/srv6-ti-lfa",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "IGP convergence eventually repairs a failed link or node, but it isn't instantaneous — and while it's still in progress, a router that simply redirects traffic toward its own new best next hop can hand it to a neighbor whose FIB hasn't converged yet, creating a genuine transient forwarding loop." },
      { id: "solution", heading: "How TI-LFA solves it", body: "RFC 9855's TI-LFA precomputes, before any failure, a repair path — an outgoing interface plus a short SRv6 repair list — from real P-Space/extended P-Space/Q-Space analysis of the current topology. On local failure detection, the Point of Local Repair activates that precomputed repair immediately: a globally-routed End.X SID with the USD flavor forces traffic through a genuinely safe node, bypassing any neighbor's stale forwarding entirely, until IGP convergence catches up and the temporary repair is released." },
    ],
  },
  {
    id: "srv6-csid",
    title: "SRv6 Compressed SID (CSID / uSID)",
    tagline: "RFC 9800 NEXT-CSID and REPLACE-CSID — folding a long SRv6 segment list into one or two 128-bit containers without changing the program's meaning.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["srv6-ti-lfa"],
    estimatedMinutes: 75,
    simulationPath: "/demo/srv6-csid",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A real SRv6 program can need many segments, and each one is a full 128-bit SID — even though most of every SID repeats the same Locator-Block and carries unused padding. Carrying that weight once per segment doesn't scale to long programs." },
      { id: "solution", heading: "How compressed SRv6 solves it", body: "RFC 9800 defines NEXT-CSID and REPLACE-CSID: a shared Locator-Block is encoded once per container instead of once per segment, with multiple compressed CSIDs (Locator-Node + Function) packed into the remaining bits. Compression only changes how the next SID is determined — Segments Left, forwarding intent, and the underlying End/End.X/End.DT4 semantics never change, and a SID with an invalid or unknown structure simply travels uncompressed alongside the rest." },
    ],
  },
  {
    id: "sr-mpls-vs-srv6",
    title: "SR-MPLS vs SRv6 Engineering Capstone",
    tagline: "The same engineering brief — shortest-path transport, explicit TE, an L3VPN, and local FRR — solved once in SR-MPLS and once in SRv6, so every difference is attributable to data-plane encoding, never to a different example.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["sr-ti-lfa", "mpls-l3vpn", "srv6-csid"],
    estimatedMinutes: 90,
    simulationPath: "/demo/sr-mpls-vs-srv6",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "SR-MPLS and SRv6 are usually taught as separate lessons on separate topologies, which makes it easy to mistake a difference in the WORKED EXAMPLE for a difference in the ARCHITECTURE. An engineer choosing between them needs to see the identical requirement solved both ways." },
      { id: "solution", heading: "How this capstone solves it", body: "One shared topology, traffic requirement, VPN service, TE requirement, and failure — implemented once in SR-MPLS (Node-SID/Adj-SID labels, LFIB, an MPLS VPN label, a label-stack repair) and once in SRv6 (End/End.X SIDs, IPv6 FIB, a Service SID via End.DT4, an End.X+USD repair) — reusing the SAME shared P-Space/Q-Space/post-convergence-path computation for both. The result is a factual, side-by-side comparison with no declared winner: two data-plane encodings of RFC 8402's one Segment Routing architecture." },
    ],
  },
  {
    id: "bgp-route-reflector",
    title: "BGP Route Reflector",
    tagline: "Full-mesh iBGP explodes past a handful of routers — a Route Reflector replaces it with hub-and-spoke.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["bgp-fundamentals"],
    estimatedMinutes: 30,
    simulationPath: "/demo/bgp-route-reflector",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Ordinary iBGP requires a direct session between every pair of routers in an AS — n(n-1)/2 sessions. At 10 routers that's 45 sessions; at 100, nearly 5,000. Every one of them is real configuration, real memory, and a real monitoring alert." },
      { id: "solution", heading: "How Route Reflection solves it", body: "A Route Reflector is an ordinary iBGP speaker allowed to re-advertise a route learned from one client to its other clients — the one deliberate exception to iBGP split-horizon. PE routers peer with the RR instead of each other; ORIGINATOR_ID and CLUSTER_LIST keep reflected routes loop-free." },
    ],
  },
  {
    id: "evpn-vxlan-foundations",
    title: "EVPN + VXLAN Foundations",
    tagline: "VTEP + VNI + BGP EVPN Type 2 — one broadcast domain, stretched across a routed fabric.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["bgp-fundamentals"],
    estimatedMinutes: 30,
    simulationPath: "/demo/evpn-vxlan",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A modern data-center fabric is routed (Layer 3) for scale, but tenants still expect two hosts in the same VLAN to behave as if they share one wire — even when a routed spine sits between their leaf switches." },
      { id: "solution", heading: "How EVPN + VXLAN solve it", body: "VXLAN encapsulates the original Ethernet frame inside IP/UDP so it can cross the routed underlay between two VTEPs; BGP EVPN Route Type 2 distributes exactly which VTEP owns which MAC/IP, replacing flood-and-learn with a verifiable control plane." },
    ],
  },
  {
    id: "evpn-bum-type3",
    title: "EVPN BUM Handling + Route Type 3 (IMET)",
    tagline: "Broadcast, unknown-unicast, multicast — and the flood list that tells a VTEP where to replicate them.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations"],
    estimatedMinutes: 30,
    simulationPath: "/demo/evpn-bum",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Route Type 2 tells a VTEP exactly where one known MAC/IP lives — but a broadcast, unknown-unicast, or multicast frame has no single destination to look up at all." },
      { id: "solution", heading: "How Route Type 3 solves it", body: "Each VTEP advertises an Inclusive Multicast Ethernet Tag (IMET) route announcing its own participation in a VNI. Every other VTEP uses these routes to build a flood list, then the ingress VTEP itself creates one independent VXLAN copy per remote participant — ingress replication." },
    ],
  },
  {
    id: "evpn-irb-anycast-gateway",
    title: "EVPN IRB + Distributed Anycast Gateway",
    tagline: "A gateway that lives on every relevant leaf, routing between subnets over a symmetric IRB / L3 VNI.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations"],
    estimatedMinutes: 35,
    simulationPath: "/demo/evpn-irb",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Two hosts in different IP subnets need to communicate through the same VXLAN fabric — bridging alone can never get a frame across a subnet boundary; something has to route it." },
      { id: "solution", heading: "How Distributed Anycast Gateway + Symmetric IRB solve it", body: "Every leaf serving a subnet provides the identical gateway IP and MAC locally — no centralized router, no hairpinning. The ingress leaf routes the frame into a VRF and a routed L3 VNI; the egress leaf routes it back out to the destination subnet — symmetric IRB, routing at both ends." },
    ],
  },
  {
    id: "evpn-type5-prefix",
    title: "EVPN Route Type 5 — IP Prefix Advertisement",
    tagline: "Advertising an entire IP prefix through EVPN — not one host's MAC/IP at a time.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-irb-anycast-gateway"],
    estimatedMinutes: 30,
    simulationPath: "/demo/evpn-type5",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A tenant VRF needs an entire external IP prefix — 172.16.50.0/24 — advertised across the fabric, but that prefix was never individually learned as one host's MAC/IP the way EVPN Route Type 2 works." },
      { id: "solution", heading: "How EVPN Route Type 5 solves it", body: "Type 5 advertises an IP Prefix Route: RD for uniqueness, RT for import policy, a next-hop VTEP, and an L3 VNI — installed into the remote VRF's routing table and forwarded over the exact same symmetric-IRB mechanism the previous lesson built." },
    ],
  },
  {
    id: "evpn-mac-mobility",
    title: "EVPN MAC Mobility",
    tagline: "The same endpoint, a new location — how EVPN tells every remote VTEP a host has moved.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations"],
    estimatedMinutes: 30,
    simulationPath: "/demo/evpn-mac-mobility",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "An endpoint's MAC and IP stay exactly the same when it physically moves to a different leaf — but every remote VTEP still believes it's behind the old one, and nothing about Type 2 alone tells them otherwise." },
      { id: "solution", heading: "How MAC Mobility solves it", body: "The new leaf re-advertises the same MAC/IP with a higher MAC Mobility sequence number. Remote VTEPs compare sequences — the newer advertisement wins, replacing the old forwarding state with the endpoint's real, current location." },
    ],
  },
  {
    id: "evpn-arp-nd-suppression",
    title: "EVPN ARP/ND Suppression",
    tagline: "Why flood a question the fabric already knows the answer to?",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations"],
    estimatedMinutes: 30,
    simulationPath: "/demo/evpn-arp-nd",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "An ordinary ARP (or IPv6 Neighbor Discovery) request is BUM traffic — it gets replicated to every VTEP in the VNI, even when the ingress VTEP already knows the answer from an EVPN Type 2 route it received long ago." },
      { id: "solution", heading: "How ARP/ND Suppression solves it", body: "The ingress VTEP checks its own EVPN MAC/IP binding first. If a valid, current binding exists, it answers locally with a proxy reply — zero remote VXLAN copies. If not, it falls back to ordinary flooding, exactly as before." },
    ],
  },
  {
    id: "evpn-multihoming-foundations",
    title: "EVPN Multihoming Foundations",
    tagline: "One endpoint, two active attachments — and exactly one forwarder for BUM.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations"],
    estimatedMinutes: 35,
    simulationPath: "/demo/evpn-multihoming",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A single-homed endpoint has exactly one VTEP that could ever originate its traffic — one point of failure. Attaching an endpoint to two PEs at once solves that, but now both PEs could deliver the same broadcast, creating duplicates." },
      { id: "solution", heading: "How EVPN multihoming solves it", body: "An Ethernet Segment Identifier (ESI) shared by both PEs marks the joint attachment. Type 4 routes discover the other PE on that segment, and a Designated Forwarder (DF) election — scoped to that one ESI and EVI — picks exactly one PE to forward BUM traffic, while every attached PE keeps forwarding ordinary unicast normally." },
    ],
  },
  {
    id: "evpn-aliasing-mass-withdrawal",
    title: "EVPN Aliasing + Mass Withdrawal",
    tagline: "Many eligible paths for known unicast — and one fast signal when a PE fails.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations", "evpn-multihoming-foundations"],
    estimatedMinutes: 35,
    simulationPath: "/demo/evpn-aliasing-mass-withdrawal",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A multihomed destination's known-unicast traffic doesn't have to use only the PE that originated its Type-2 route — and when one attached PE's segment link fails, the fabric shouldn't have to wait for every dependent MAC route to converge one at a time." },
      { id: "solution", heading: "How Aliasing + Mass Withdrawal solve it", body: "Ethernet A-D per-EVI routes let a remote PE build an eligible next-hop set for known unicast (Aliasing). Ethernet A-D per-ES routes carry a fast, segment-wide failure signal — withdrawing one rapidly prunes the failed PE from every dependent destination's eligible set (Mass Withdrawal)." },
    ],
  },
  {
    id: "evpn-single-active-vpws",
    title: "EVPN Single-Active + EVPN-VPWS",
    tagline: "One Primary protects a point-to-point virtual Ethernet wire.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["evpn-vxlan-foundations", "evpn-multihoming-foundations"],
    estimatedMinutes: 40,
    simulationPath: "/demo/evpn-vpws",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Some multihomed sites need exactly one PE forwarding at a time rather than several at once (Single-Active) — and some services are point-to-point, not multipoint bridged domains, so ordinary MAC-learning-based EVPN isn't the right model for them." },
      { id: "solution", heading: "How Single-Active + EVPN-VPWS solve it", body: "A Single-Active election picks one Primary and one Backup PE for a multihomed Ethernet Segment. EVPN-VPWS then rides on that redundancy: Ethernet A-D per-EVI routes — not Type-2 MAC routes — discover the remote endpoint and signal the service label for a point-to-point Ethernet service." },
    ],
  },
  {
    id: "mpls-l2vpn-vpws",
    title: "Traditional MPLS L2VPN / VPWS",
    tagline: "Attachment circuits, targeted LDP, pseudowire labels, and two-label forwarding — the classic point-to-point pseudowire.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-l3vpn", "evpn-single-active-vpws"],
    estimatedMinutes: 45,
    simulationPath: "/demo/mpls-l2vpn-vpws",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "How can two customer Ethernet ports behave like one virtual wire even though an MPLS provider network sits between them? Ordinary transport reachability between the two PEs isn't enough — the egress PE still has to know which local customer service should receive a given frame." },
      { id: "solution", heading: "How traditional LDP-signaled VPWS solves it", body: "A targeted LDP session between the two PE loopbacks signals a pseudowire FEC — PW type and PW ID — that both PEs must agree on. Each PE independently allocates and advertises its own directional receive label, so the outer transport label gets a frame to the far PE while the inner pseudowire label tells that PE which virtual wire it belongs to. P routers only ever touch the outer label, never the pseudowire state — the same signaling model EVPN-VPWS replaces with BGP." },
    ],
  },
  {
    id: "mpls-vpls",
    title: "Traditional MPLS VPLS",
    tagline: "Full-mesh pseudowires, data-plane MAC learning, BUM flooding, and pseudowire split horizon — turning point-to-point wires into one virtual LAN.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-l2vpn-vpws"],
    estimatedMinutes: 50,
    simulationPath: "/demo/mpls-vpls",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A VPWS pseudowire connects exactly two sites. How does a provider connect three or more customer sites into what looks, to the customer, like one shared Ethernet LAN — without any single pseudowire being multipoint?" },
      { id: "solution", heading: "How traditional VPLS solves it", body: "Every PE runs a per-service virtual Ethernet bridge, full-meshed with a direct pseudowire to every other PE. Each PE learns MAC addresses purely from the data plane — on its local attachment circuit and on every pseudowire alike — floods unknown/broadcast/multicast traffic, and forwards known unicast to a single port. One rule keeps the mesh loop-free: a frame received from one mesh pseudowire is never relayed out another mesh pseudowire (split horizon), which is exactly why the mesh must be full in the first place." },
    ],
  },
  {
    id: "bgp-vpls",
    title: "BGP-Signaled VPLS",
    tagline: "RFC 4761 BGP auto-discovery, VE IDs, and label-block PW signaling — replacing targeted LDP with MP-BGP over a Route Reflector, without changing how MACs are learned.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-vpls", "bgp-route-reflector"],
    estimatedMinutes: 55,
    simulationPath: "/demo/bgp-vpls",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "Targeted LDP works, but every PW still needed its own manually-configured, per-pair session — nothing discovers VPLS membership automatically, and nothing signals a new PE's pseudowires without touching every existing PE." },
      { id: "solution", heading: "How BGP-signaled VPLS solves it", body: "RFC 4761 replaces targeted LDP with MP-BGP: each PE advertises an RD, a Route Target, a VE ID, and a label block (VE Block Offset + Size + Label Base) over a Route Reflector. A Route Target match auto-discovers membership; the actual per-pair label is derived from the label block and the sender's own VE ID, never read off the advertisement directly. Crucially, BGP never carries a customer MAC address — remote MAC learning stays exactly what it always was in classic VPLS: data-plane source-MAC learning, flooding, and split horizon." },
    ],
  },
  {
    id: "h-vpls",
    title: "Hierarchical VPLS",
    tagline: "MTU-s access bridges, spoke pseudowires, and a smaller PE-rs core mesh — RFC 4762's answer to a flat VPLS mesh that can't scale to dozens of access sites.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-vpls"],
    estimatedMinutes: 55,
    simulationPath: "/demo/h-vpls",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "A flat VPLS mesh costs n(n-1)/2 pseudowires. If dozens or hundreds of access sites need the same service, must every one of them become another full-mesh core PE, paying that same quadratic cost as the mesh grows?" },
      { id: "solution", heading: "How H-VPLS solves it", body: "RFC 4762 splits the service into two tiers. Access-tier MTU-s bridges reach the service through exactly one spoke pseudowire to a PE-rs hub; only the PE-rs tier maintains a (much smaller) core full mesh. The split-horizon rule generalizes accordingly: a spoke PW behaves like an access-side bridging port — AC, spoke, and mesh may all freely forward to one another — and only mesh-to-mesh relay stays forbidden, the one loop-prevention rule carried over unchanged from flat VPLS." },
    ],
  },
  {
    id: "l2vpn-evolution",
    title: "L2VPN Evolution Capstone",
    tagline: "VPWS → LDP-VPLS → BGP-VPLS → H-VPLS → EVPN — one customer, five architectures, compared on discovery, MAC reachability, BUM, split horizon, and multihoming.",
    category: "service-provider",
    difficulty: "expert",
    prerequisites: ["mpls-l2vpn-vpws", "mpls-vpls", "bgp-vpls", "h-vpls", "evpn-vxlan-foundations", "evpn-multihoming-foundations", "evpn-mac-mobility"],
    estimatedMinutes: 60,
    simulationPath: "/demo/l2vpn-evolution",
    tier: "pro",
    sections: [
      { id: "problem", heading: "The problem", body: "VPWS, VPLS, BGP-VPLS, H-VPLS, and EVPN can all provide some form of Layer-2 service. If one architecture can already do it, why do all five exist — and which one should an engineer actually reach for?" },
      { id: "solution", heading: "How this capstone answers it", body: "The same customer, CUST-A, is carried across all five architectures. Each one changes exactly one axis: VPWS solves point-to-point transport; VPLS makes it multipoint; BGP-VPLS changes discovery/signaling without touching MAC learning; H-VPLS changes topology/hierarchy without touching MAC learning; EVPN is the one that changes the Ethernet control-plane model itself, distributing MAC/IP reachability through BGP." },
    ],
  },
];

export const getLessonById = (id: string) => lessons.find((l) => l.id === id);
