import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the MPLS L3VPN lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question steps, so they never state an answer. */
export const L3VPN_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Connect Customer A's two sites privately across a shared provider core.", steps: ["intro", "predict-problem", "prerequisites"] },
  { phase: { label: "VRF", tone: "violet" }, objective: "Keep each customer's routes in its own table on the PE.", steps: ["vrf-intro", "predict-vrf", "overlap-intro", "predict-overlap"] },
  { phase: { label: "RD & RT", tone: "bgp" }, objective: "Separate the job that makes VPN routes unique from the job that decides where they are imported.", steps: ["rd-intro", "predict-rd", "rt-intro", "rd-vs-rt-table", "predict-rd-vs-rt"] },
  { phase: { label: "Control plane", tone: "bgp" }, objective: "Build PE2's VPNv4 route for 10.2.2.0/24 and get it into PE1's VRF CUST-A.", steps: ["mpbgp-intro", "remote-route-learned", "add-rd", "rt-attach", "vpn-label-alloc", "mpbgp-advertise", "predict-rt-import", "rt-import-check", "vrf-install", "control-recap"] },
  { phase: { label: "Data plane: ingress", tone: "mpls" }, objective: "Work out what PE1 puts on CE1's packet before it enters the core.", steps: ["send-ce1", "vrf-lookup", "predict-two-labels", "predict-stack-order", "push-vpn-label", "push-transport-label"] },
  { phase: { label: "Data plane: core", tone: "mpls" }, objective: "Watch what P1 and P2 do, and don't do, with each label.", steps: ["p1-swap", "predict-p-router", "p2-php", "predict-remaining-label"] },
  { phase: { label: "Data plane: egress", tone: "success" }, objective: "Deliver the packet into the right customer at PE2.", steps: ["pe2-vpn-lookup", "pe2-deliver", "journey-recap"] },
  { phase: { label: "Route builder", tone: "violet" }, objective: "Rebuild PE2's VPNv4 route one field at a time.", steps: ["route-builder-rd", "route-builder-rt", "route-builder-nexthop", "route-builder-label"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "MP-BGP is up but the route is missing from CUST-A. Find the layer where it disappears.", steps: ["break-intro", "fault-injected", "trouble-intro", "trouble-question", "diagnostic-layers"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores CUST-A's route.", steps: ["repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with real traffic, not just a route.", steps: ["verify-dataplane"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review which piece did which job.", steps: ["complete"] },
];

export const L3VPN_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  intro: { doingNow: "The core carries many customers and must not hold their routes." },
  "predict-problem": { doingNow: "Consider what must be kept separate, and where." },
  prerequisites: { doingNow: "OSPF, LDP and the PE1 → PE2 transport LSP already work.", takeaway: "Transport is solved; this lesson adds the VPN layer on top." },
  "vrf-intro": { doingNow: "PE1 has a global table and a separate VRF CUST-A." },
  "predict-vrf": { doingNow: "Ask which table the provider core's routers use." },
  "overlap-intro": { doingNow: "Customer B uses the same 10.1.1.0/24 in its own VRF." },
  "predict-overlap": { doingNow: "Both identical prefixes will share the same MP-BGP session." },
  "predict-rd": { doingNow: "Re-read the RD step and be precise." },
  "rt-intro": { doingNow: "An export RT is attached on send; an import RT is checked on receive." },
  "rd-vs-rt-table": { takeaway: "VRF separates, RD makes unique, RT decides import." },
  "predict-rd-vs-rt": { doingNow: "Revisit the RD vs. RT comparison before answering." },
  "mpbgp-intro": { doingNow: "Control plane: PE1 and PE2 already have a VPNv4 MP-BGP session." },
  "remote-route-learned": { doingNow: "PE2 learns 10.2.2.0/24 from CE2 into VRF CUST-A." },
  "add-rd": { doingNow: "Control plane: PE2 prepends its RD, making a VPNv4 route." },
  "rt-attach": { doingNow: "Control plane: PE2 attaches its export RT." },
  "vpn-label-alloc": { doingNow: "Control plane: PE2 allocates a VPN (service) label, separate from any transport label." },
  "mpbgp-advertise": { doingNow: "Control plane: one VPNv4 UPDATE carries RD, prefix, RT, next hop and VPN label." },
  "predict-rt-import": { doingNow: "Recall what the import check decides." },
  "vrf-install": { takeaway: "Received is not the same as imported: RT decides." },
  "control-recap": { takeaway: "IGP → PE loopback. LDP → transport label. MP-BGP → VPN route + VPN label." },
  "send-ce1": { doingNow: "Data plane: CE1 sends plain IP toward 10.2.2.20." },
  "vrf-lookup": { doingNow: "Data plane: PE1 looks up the destination in VRF CUST-A, not the global table." },
  "predict-two-labels": { doingNow: "Think about everything PE1 learned for this destination." },
  "predict-stack-order": { doingNow: "Consider who reads the stack at each hop." },
  "push-vpn-label": { doingNow: "Data plane: the first label pushed becomes the bottom of the stack." },
  "push-transport-label": { doingNow: "Data plane: a second label goes on top; the bottom label keeps S=1.", takeaway: "OUTER = transport (S=0), INNER = VPN (S=1)." },
  "p1-swap": { doingNow: "Data plane: P1 swaps the outer label only; the inner label rides along untouched." },
  "predict-p-router": { doingNow: "Consider what P1 actually looked up to forward." },
  "p2-php": { doingNow: "Data plane: P2 pops the outer label only." },
  "predict-remaining-label": { doingNow: "Think about what PE2 must still decide when the packet arrives." },
  "pe2-vpn-lookup": { doingNow: "PE2 uses the remaining label to find VRF CUST-A." },
  "pe2-deliver": { doingNow: "PE2 removes the last label and forwards plain IP to CE2." },
  "journey-recap": { takeaway: "The control plane built every value the data plane used." },
  "route-builder-rd": { doingNow: "Recall who originates this route and in which VRF." },
  "route-builder-rt": { doingNow: "Recall how the receiving PE decides what to import." },
  "route-builder-nexthop": { doingNow: "Recall what the BGP next hop is used for in the data plane." },
  "route-builder-label": { doingNow: "Recall which router allocated the label and for which purpose." },
  "fault-injected": { doingNow: "PE1's CUST-A import policy was changed." },
  "trouble-intro": { doingNow: "Check the session, the received VPNv4 route, its RD/RT, then the VRF table." },
  "trouble-question": { doingNow: "Walk the layers bottom-up and stop at the first one that fails." },
  "diagnostic-layers": { takeaway: "An Established session doesn't mean every route is imported." },
  "repair-challenge": { doingNow: "Fix the layer you identified. Wrong choices explain why." },
  "verify-dataplane": { doingNow: "Data plane: a fresh packet crosses the two-label stack end to end." },
};
