import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the H-VPLS lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/challenge steps, so they never state an answer. */
export const HVPLS_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Extend one VPLS to many access sites without growing the full mesh.", steps: ["intro", "recap-flat-vpls", "predict-flat-scaling", "central-question"] },
  { phase: { label: "Hierarchy", tone: "violet" }, objective: "Learn the two tiers, their devices and their pseudowire types.", steps: ["hierarchy-mental-model", "terminology-mtu-pe", "terminology-spoke-mesh", "why-hierarchy-flat-example", "why-hierarchy-hierarchical-example", "predict-hierarchy-savings", "topology-intro", "customer-service-intro", "mtu-is-a-bridge", "predict-mtu-role"] },
  { phase: { label: "Core mesh", tone: "mpls" }, objective: "Build the PE-rs core mesh on top of the transport.", steps: ["transport-recap", "transport-lsp-up", "core-mesh-intro", "establish-mesh-pe1-pe2", "establish-mesh-pe1-pe3", "establish-mesh-pe2-pe3"] },
  { phase: { label: "Spoke setup", tone: "violet" }, objective: "Attach each MTU-s to its hub and inspect the bridge port roles.", steps: ["spoke-pw-intro", "establish-spoke-mtu1-pe1", "establish-spoke-mtu2-pe2", "establish-spoke-mtu3-pe3", "predict-spoke-signaling", "bridge-ports-mtu1", "bridge-ports-pe1", "predict-port-roles", "ready-but-empty"] },
  { phase: { label: "MAC learning", tone: "success" }, objective: "Send the first frame and watch MTU1 learn and decide.", steps: ["local-switching-intro", "send-ce1-to-ce2-1", "mtu1-learn-ce1", "predict-unknown-at-mtu", "mtu1-flood-decision", "ce2-receives-directly"] },
  { phase: { label: "BUM through the hierarchy", tone: "warning" }, objective: "Follow flooded copies from spoke to core and back down.", steps: ["pe1-receives-spoke-copy", "predict-spoke-to-mesh", "pe2-receives-mesh-delivers-spoke", "pe3-receives-direct-from-pe1", "mtu2-mtu3-discard", "predict-mesh-to-mesh"] },
  { phase: { label: "Local switching", tone: "success" }, objective: "See what happens to traffic between two sites on the same MTU-s.", steps: ["ce2-replies", "mtu1-local-deliver-ce1", "send-ce1-to-ce2-2-local", "signature-local-switching-visual", "predict-local-switching", "predict-spoke-failure-preview"] },
  { phase: { label: "Forwarding", tone: "mpls" }, objective: "Send genuinely remote traffic through spoke, mesh and spoke.", steps: ["remote-traffic-intro", "send-ce1-to-ce3", "mtu1-flood-remote", "pe1-spoke-ingress-relearn-flood", "pe2-mesh-ingress-delivers-ce3", "mtu2-delivers-ce3", "pe3-mtu3-discard-path", "ce3-responds", "known-unicast-hierarchy-path", "mac-tables-hierarchical-perspectives", "predict-fdb-sync", "ce1-to-ce4-intro", "send-ce1-to-ce4", "ce4-replies-known", "compare-local-vs-remote"] },
  { phase: { label: "Scaling", tone: "cyan" }, objective: "Compare flat and hierarchical designs, and what each tier still does.", steps: ["scaling-lab-intro", "why-access-scales-better", "core-still-has-responsibility", "flat-vs-hvpls-comparison", "bgp-vpls-orthogonality", "evpn-preview"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "Every PW is UP, yet remote sites can't be reached from MTU1. Find why.", steps: ["troubleshooting-intro", "fault-injection", "why-local-still-works", "demonstrate-fault", "signature-fault-visual", "diagnostic-ladder", "trouble-question"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores remote reachability.", steps: ["repair-challenge", "repaired-recompute"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real CE1 → CE3 frame.", steps: ["verify-send-ce1-ce3", "verify-spoke-to-mesh-restored", "verify-delivered-ce3"] },
  { phase: { label: "Failure", tone: "danger" }, objective: "Fail a spoke outright and see which traffic survives.", steps: ["optional-spoke-failure-intro", "fail-mtu1-spoke", "local-survival-demo", "predict-spoke-failure-confirmed", "restore-spoke"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Confirm every piece of the hierarchy you built.", steps: ["engineer-challenge-intro", "engineer-challenge-confirm"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review the tiers, the port roles and the refined split horizon.", steps: ["complete"] },
];

export const HVPLS_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "predict-flat-scaling": { doingNow: "Use the full-mesh formula n(n−1)/2." },
  "topology-intro": { doingNow: "CE1+CE2 → MTU1 → PE1; CE3 → MTU2 → PE2; CE4 → MTU3 → PE3." },
  "mtu-is-a-bridge": { takeaway: "An MTU-s is a real bridge with its own FDB." },
  "predict-mtu-role": { doingNow: "Think about how many PWs MTU1 needs to reach the service." },
  "establish-mesh-pe1-pe2": { doingNow: "Control plane: mesh PW PE1 ↔ PE2 (PE1 receives 24012, PE2 receives 25021)." },
  "establish-spoke-mtu1-pe1": { doingNow: "Control plane: spoke PW MTU1 ↔ PE1 (PE1 receives 34011, MTU1 receives 44011)." },
  "establish-spoke-mtu2-pe2": { doingNow: "Control plane: spoke PW MTU2 ↔ PE2 (PE2 receives 34022, MTU2 receives 44022)." },
  "establish-spoke-mtu3-pe3": { doingNow: "Control plane: spoke PW MTU3 ↔ PE3 (PE3 receives 34033, MTU3 receives 44033)." },
  "predict-spoke-signaling": { doingNow: "Compare how the spoke labels were allocated with the mesh labels." },
  "bridge-ports-pe1": { doingNow: "PE1's ports: SPOKE_PW: MTU1, MESH_PW: PE2, MESH_PW: PE3." },
  "predict-port-roles": { doingNow: "Consider whether both PW kinds should be treated the same way." },
  "send-ce1-to-ce2-1": { doingNow: "Data plane: CE1 (00:11:11:11:11:11) → CE2 (00:22:22:22:22:22), both behind MTU1." },
  "predict-unknown-at-mtu": { doingNow: "List MTU1's ports and which one the frame came in on." },
  "pe1-receives-spoke-copy": { doingNow: "Data plane: the spoke copy arrives at PE1 with transport 901 (S0) over PE1's spoke label 34011 (S1)." },
  "predict-spoke-to-mesh": { doingNow: "Recall which rule was refined for H-VPLS." },
  "pe2-receives-mesh-delivers-spoke": { doingNow: "Data plane: PE2 got the copy on a mesh PW. Check which egress ports remain." },
  "predict-mesh-to-mesh": { doingNow: "Think about what a core mesh PE may relay." },
  "signature-local-switching-visual": { takeaway: "Once learned, CE1 ↔ CE2 never touches the spoke." },
  "predict-local-switching": { doingNow: "Look at where both MACs are learned at MTU1." },
  "predict-spoke-failure-preview": { doingNow: "Consider which ports local traffic uses." },
  "pe1-spoke-ingress-relearn-flood": { doingNow: "Data plane: PE1 receives on its spoke and floods to both mesh peers." },
  "pe2-mesh-ingress-delivers-ce3": { doingNow: "Data plane: PE2 sends down its spoke: transport 802 (S0) over MTU2's label 44022 (S1)." },
  "mac-tables-hierarchical-perspectives": { takeaway: "Same MAC, a different port at every device." },
  "predict-fdb-sync": { doingNow: "Recall how every entry so far was learned." },
  "compare-local-vs-remote": { takeaway: "Local: MTU only. Remote: spoke → mesh → spoke." },
  "fault-injection": { doingNow: "PE1's configuration toward MTU1 changed; the pseudowire itself stays UP." },
  "why-local-still-works": { doingNow: "The fault is at PE1, one hop beyond MTU1's bridge." },
  "signature-fault-visual": { doingNow: "Data plane: watch which egress ports PE1 keeps for the frame." },
  "diagnostic-ladder": { doingNow: "Walk up: interfaces, transport, spoke PW state, mesh PW state, MAC learning, port roles." },
  "trouble-question": { doingNow: "Match what you observed at PE1 with the forwarding rules." },
  "repair-challenge": { doingNow: "Pick the repair that fixes what you diagnosed. Wrong choices explain why." },
  "verify-spoke-to-mesh-restored": { doingNow: "Data plane: PE1 floods from its spoke to both mesh peers again." },
  "fail-mtu1-spoke": { doingNow: "MTU1's spoke to PE1 goes down for real." },
  "predict-spoke-failure-confirmed": { doingNow: "Compare with your earlier prediction." },
};
