import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for SRv6 CSID — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. */
export const SRV6C_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "See why a long SRv6 program carries so much repeated SID data.", steps: ["intro", "problem-answer", "usid-naming-note", "predict-usid-normative"] },
  { phase: { label: "Principle", tone: "violet" }, objective: "Separate what compression changes from what it must preserve.", steps: ["compression-changes-encoding", "predict-changes-endx-semantics"] },
  { phase: { label: "SID structure", tone: "violet" }, objective: "Take the SID structure apart: LBL, LNL, FL, AL.", steps: ["sid-anatomy-refresher", "terminology-table", "layout-intro", "capacity-calc", "predict-capacity-check"] },
  { phase: { label: "Setup", tone: "ospf" }, objective: "Meet the chain, the shared Locator-Block and the logical program.", steps: ["topology-intro", "locator-block-intro", "logical-program-intro"] },
  { phase: { label: "Validation", tone: "warning" }, objective: "Check every advertised structure before compressing anything.", steps: ["structure-model-intro", "validate-all-structures", "predict-not-every-sid-compressible"] },
  { phase: { label: "Containers", tone: "ip" }, objective: "Build the compressed containers and the SRH that carries them.", steps: ["uncompressed-program", "compress-first-container", "not-five-ipv6-addresses", "compress-second-container", "full-srh-two-containers", "predict-forward-vs-reverse", "predict-srh-entries-reverse"] },
  { phase: { label: "NEXT-CSID walk", tone: "ip" }, objective: "Follow the program hop by hop and track DA, Segments Left and Hop Limit.", steps: ["r1-imposes", "r1-forward", "r2-match-execute", "predict-sl-during-shift", "predict-why-sl-unchanged", "predict-hop-limit-behavior", "r2-forward", "r3-r5-shift", "r6-boundary-cross", "predict-sl-at-boundary", "r7-r8-finish"] },
  { phase: { label: "One container", tone: "cyan" }, objective: "Compress a shorter program and read the packet it produces.", steps: ["one-container-intro", "predict-one-container-no-srh", "one-container-no-fake-srh"] },
  { phase: { label: "End.X", tone: "warning" }, objective: "Run the same flavor on an End.X segment and compare the forwarding.", steps: ["endx-intro", "endx-setup", "predict-endx-forwarding", "endx-walk", "endx-r8-final"] },
  { phase: { label: "Service SID", tone: "bgp" }, objective: "Finish a compressed run on a real service SID.", steps: ["next-csid-restriction", "predict-dt4-next-defined", "final-service-sid-experiment", "predict-last-sid-no-flavor-required", "structure-invariants", "mixed-flavor-preview"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "The expected compressed encoding is not produced. Find out why.", steps: ["troubleshooting-intro", "diagnostic-ladder", "trouble-question", "fault-consequence"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Rule out the tempting fixes, then apply the one that addresses the cause.", steps: ["wrong-repair-metric", "wrong-repair-preference", "wrong-repair-ignore-structure", "repair-challenge", "apply-repair"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Resend and prove the logical program is unchanged.", steps: ["mandatory-resend"] },
  { phase: { label: "Metrics", tone: "cyan" }, objective: "Measure segment-value storage — and what it is not.", steps: ["compression-comparison", "compression-metrics-viewer", "mtu-lab", "header-efficiency-lab"] },
  { phase: { label: "REPLACE-CSID", tone: "violet" }, objective: "Build and walk the other CSID flavor, with its own layout and Index.", steps: ["replace-csid-intro", "replace-layout", "predict-replace-capacity", "replace-first-container", "replace-packed-containers", "predict-packed-not-copied", "replace-advance-walk", "predict-replace-index-order", "replace-dt4-execute", "predict-dt4-replace-defined", "flavor-comparison", "mixed-experiment"] },
  { phase: { label: "Deployment", tone: "ospf" }, objective: "Preview allocation, control-plane needs and integration with policy and TI-LFA.", steps: ["gib-lib-intro", "global-plus-local", "operational-guidance", "control-plane-preview", "compression-source", "sr-policy-integration", "tilfa-integration"] },
  { phase: { label: "Challenge", tone: "danger" }, objective: "Diagnose and fix a fresh, independent fault on your own.", steps: ["challenge-intro", "challenge-inject-fault", "challenge-diagnose", "challenge-repair", "challenge-verify", "challenge-replace-confirm"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review both CSID flavors, validation and equivalence.", steps: ["complete"] },
];

export const SRV6C_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "layout-intro": { doingNow: "Main lab: LBL 48, CSID (LNFL) 16 bits." },
  "locator-block-intro": { doingNow: "Shared Locator-Block 2001:db8:c5::/48; R2..R8 own Locator-Nodes 0x0002..0x0008." },
  "validate-all-structures": { doingNow: "Every router advertises 48/16/0/64 — AL = 128 − 48 − 16 − 0." },
  "uncompressed-program": { doingNow: "7 × 16 = 112 bytes of segment-value storage (not total packet size)." },
  "compress-first-container": { doingNow: "Container A: Locator-Block | R2 R3 R4 R5 R6." },
  "compress-second-container": { doingNow: "Container B: Locator-Block | R7 R8 | padding." },
  "r1-imposes": { doingNow: "DA = Container A; SRH [0] = Container B, [1] = Container A; SL 1; Hop Limit 64." },
  "r2-match-execute": { doingNow: "Shown after R2's shift: R3's CSID is active, SL unchanged, Hop Limit 63." },
  "r3-r5-shift": { doingNow: "Shown after R5's shift: R6's CSID is active, SL still 1, Hop Limit 60." },
  "r6-boundary-cross": { doingNow: "Shown after the boundary: Container B active, SL 0, Hop Limit 59.", takeaway: "Segments Left changes only when a new 128-bit entry is consumed." },
  "r7-r8-finish": { doingNow: "R7 shifts (Hop Limit 58); R8's CSID is final." },
  "endx-walk": { doingNow: "Shown after R6's End.X: Container B (R8) active, forced over R6→R8; R7 bypassed." },
  "final-service-sid-experiment": { doingNow: "The last Segment List entry is PE2's ordinary End.DT4 SID." },
  "troubleshooting-intro": { doingNow: "Policy valid, every SID reachable — but the expected encoding is missing." },
  "fault-consequence": { doingNow: "Three entries: Container(R2,R3), ordinary R4, Container(R5..R8) — same logical program." },
  "repair-challenge": { doingNow: "Choose the change that fixes the cause you identified." },
  "mandatory-resend": { doingNow: "Back to two containers; the expanded program equals the original.", takeaway: "Equivalence is verified, never assumed." },
  "compression-comparison": { doingNow: "112 bytes → 32 bytes of segment-value storage." },
  "replace-layout": { doingNow: "REPLACE lab: LBL 48, CSID 32 bits (Locator-Node 16 + Function 16), K = 4." },
  "replace-packed-containers": { doingNow: "Packed physical positions: 3 = R3, 2 = R4, 1 = R8 End.DT4, 0 = padding." },
  "replace-advance-walk": { doingNow: "Index 0 → 3 → 2 → 1; Hop Limit 64 → 63 → 62 → 61; R8 End.DT4 active.", takeaway: "Physical position order is not processing order." },
  "challenge-inject-fault": { doingNow: "A fresh fault, independent of the earlier one." },
  "challenge-repair": { doingNow: "Choose the fix for the cause you diagnosed." },
};
