import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the MPLS/LDP lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question steps, so they never state an answer. */
export const LDP_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Carry CE1's traffic across the provider core using labels instead of a per-hop IP lookup.", steps: ["intro", "predict-problem", "terminology", "igp-converged"] },
  { phase: { label: "FEC", tone: "mpls" }, objective: "Pin down what a label actually stands for before any label is advertised.", steps: ["fec-intro", "predict-fec"] },
  { phase: { label: "LDP discovery", tone: "mpls" }, objective: "Bring up LDP neighbors: discovery first, then a session.", steps: ["ldp-discovery-intro", "ldp-hello", "ldp-session", "ldp-other-sessions"] },
  { phase: { label: "Control plane", tone: "violet" }, objective: "Distribute labels for 4.4.4.4/32 upstream from PE2 and build the LIB and LFIB.", steps: ["label-dist-pe2", "label-dist-p2", "label-dist-p1", "lfib-pe1", "lib-vs-lfib"] },
  { phase: { label: "Data plane", tone: "success" }, objective: "Follow one packet from CE1 into the LSP and name the label operation at each router.", steps: ["predict-ingress", "send-ce1", "push-pe1", "inspect-shim", "predict-transit", "swap-p1", "predict-inspect-ip"] },
  { phase: { label: "Penultimate hop", tone: "mpls" }, objective: "Work out what the last core router does with the label, and why.", steps: ["implicit-null-intro", "predict-php", "pop-p2", "why-php", "egress-pe2"] },
  { phase: { label: "Two planes", tone: "violet" }, objective: "Separate what OSPF and LDP decide from what the forwarding plane does.", steps: ["control-vs-data", "predict-igp-dependency"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "IP reachability is healthy but the LSP is broken. Find the layer that failed.", steps: ["break-intro", "fault-injected", "trouble-intro", "trouble-question"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores the LSP on P1 ↔ P2.", steps: ["repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with real traffic across the whole LSP.", steps: ["verify-repair", "verify-push", "verify-swap", "verify-pop"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review how LDP built the LSP and how the data plane used it.", steps: ["complete"] },
];

export const LDP_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  intro: { doingNow: "No labels exist yet. Every router still routes by IP destination." },
  "predict-problem": { doingNow: "Think about what each router in the core has to look at today." },
  terminology: { doingNow: "CE routers sit outside MPLS; PEs are the edge (LER), Ps are the core (LSR)." },
  "igp-converged": { doingNow: "OSPF already reaches every loopback, including PE2's 4.4.4.4/32.", takeaway: "LDP labels what the IGP can already reach." },
  "predict-fec": { doingNow: "Recall the definition on the previous step before answering." },
  "ldp-hello": { doingNow: "Control plane: PE1 and P1 discover each other with Hellos on UDP 646. No labels yet." },
  "ldp-session": { doingNow: "Control plane: a TCP 646 session forms. This is what will carry label mappings.", takeaway: "Discovery (UDP) and session (TCP) are separate steps." },
  "ldp-other-sessions": { doingNow: "P1↔P2 and P2↔PE2 run the same Hello → session sequence." },
  "label-dist-pe2": { doingNow: "PE2 owns 4.4.4.4/32 and advertises implicit-null to P2." },
  "label-dist-p2": { doingNow: "P2 allocates its own local label for the FEC and advertises it to P1." },
  "label-dist-p1": { doingNow: "P1 allocates its own local label and advertises it to PE1.", takeaway: "Labels are local to each router and flow upstream, against the traffic." },
  "lfib-pe1": { doingNow: "PE1 combines IGP reachability with P1's advertised label into an LFIB entry." },
  "lib-vs-lfib": { takeaway: "LIB = every binding heard. LFIB = only the ones used to forward." },
  "predict-ingress": { doingNow: "An unlabeled packet is arriving at the edge of the MPLS domain." },
  "send-ce1": { doingNow: "Data plane: CE1 sends a plain IP packet toward 10.2.2.20." },
  "push-pe1": { doingNow: "Data plane: PE1 classifies the packet to the FEC and pushes a label." },
  "inspect-shim": { doingNow: "Open the MPLS shim in the Packet Inspector: Label, TC, S and TTL." },
  "predict-transit": { doingNow: "Read P1's LFIB entry for the incoming label before answering." },
  "swap-p1": { doingNow: "Data plane: P1 swaps the top label using only its LFIB." },
  "predict-inspect-ip": { doingNow: "Consider which header P1's lookup actually used." },
  "implicit-null-intro": { doingNow: "implicit-null is a signaling value, never a label written on the wire." },
  "predict-php": { doingNow: "Recall what PE2 advertised upstream and what that value asks for." },
  "pop-p2": { doingNow: "Data plane: P2 removes the label before handing the packet to PE2." },
  "why-php": { takeaway: "PHP saves the egress PE a second lookup." },
  "egress-pe2": { doingNow: "PE2 delivers to CE2 with an ordinary IP lookup." },
  "control-vs-data": { takeaway: "OSPF and LDP build state; PUSH/SWAP/POP only use it." },
  "predict-igp-dependency": { doingNow: "Think about what LDP labels in the first place." },
  "fault-injected": { doingNow: "The LDP session between P1 and P2 is down. OSPF is untouched." },
  "trouble-intro": { doingNow: "Check the IGP table, LDP neighbors, LIB, LFIB and interfaces in that order." },
  "trouble-question": { doingNow: "Walk the layers bottom-up and stop at the first one that fails." },
  "repair-challenge": { doingNow: "Pick the repair that fixes the layer you identified. Wrong choices explain why." },
  "verify-repair": { doingNow: "Data plane: a fresh packet from CE1 tests the rebuilt LSP." },
  "verify-push": { doingNow: "PE1 pushes the same label as before the fault." },
  "verify-swap": { doingNow: "P1 has an LFIB entry again and swaps toward P2." },
  "verify-pop": { doingNow: "P2 pops (PHP) and PE2 delivers to CE2.", takeaway: "Same LDP mechanics, same labels: the LSP is back." },
};
