import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the VPWS lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/challenge steps, so they never state an answer. */
export const VPWS_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Make CE1 and CE2 behave like two ends of one Ethernet wire across the MPLS core.", steps: ["intro", "recap-known", "mental-model", "topology-intro", "customer-requirement"] },
  { phase: { label: "Attachment circuit", tone: "ip" }, objective: "Identify where the service begins and ends on each PE.", steps: ["attachment-circuit-intro", "service-instance-intro", "vlan-vs-pwid"] },
  { phase: { label: "Transport", tone: "mpls" }, objective: "Confirm PE-to-PE MPLS transport and see what it does not provide.", steps: ["transport-recap-intro", "igp-up", "ldp-transport-up", "transport-lsp-up", "predict-transport-implies-pw", "pw-still-down", "transport-lsp-vs-pw", "why-ldp-not-enough"] },
  { phase: { label: "Targeted LDP", tone: "violet" }, objective: "Bring up the PE1 ↔ PE2 signaling session between loopbacks.", steps: ["targeted-ldp-intro", "targeted-ldp-visual", "targeted-ldp-lifecycle-intro", "targeted-hello", "targeted-tcp", "targeted-init", "targeted-operational", "tcp-distinction"] },
  { phase: { label: "PW signaling", tone: "violet" }, objective: "Agree on which pseudowire both PEs are describing.", steps: ["pw-fec-intro", "pw-fec-defined", "pw-id-vs-label", "predict-pwid-is-label"] },
  { phase: { label: "Service labels", tone: "mpls" }, objective: "Allocate and advertise one receive label per direction.", steps: ["directional-label-alloc-intro", "pe1-allocates-label", "pe2-allocates-label", "label-mapping-pe1-to-pe2", "label-mapping-pe2-to-pe1", "predict-same-pw-label"] },
  { phase: { label: "PW up", tone: "success" }, objective: "Check every condition the pseudowire needs to come up.", steps: ["pw-up-criteria-intro", "pw-up", "predict-p-router-pwid"] },
  { phase: { label: "Encapsulation", tone: "mpls" }, objective: "Watch PE1 turn CE1's Ethernet frame into a labeled MPLS packet.", steps: ["packet-before-encap", "pe1-ac-ingress", "pe1-push-pw", "pe1-push-transport", "two-label-stack-signature"] },
  { phase: { label: "Core forwarding", tone: "mpls" }, objective: "Follow the packet through P1 and P2.", steps: ["p1-transport-forward", "p2-transport-forward-php", "p-router-knowledge-boundary"] },
  { phase: { label: "Decapsulation", tone: "success" }, objective: "Deliver the frame to the right attachment circuit at PE2.", steps: ["pe2-egress-intro", "predict-egress-label", "pe2-pw-lookup", "pe2-deliver"] },
  { phase: { label: "Reverse direction", tone: "violet" }, objective: "Send CE2 → CE1 and compare the labels used in each direction.", steps: ["reverse-direction-intro", "ce2-sends", "pe2-push-reverse", "core-reverse-forward", "core-reverse-php", "pe1-reverse-lookup-deliver", "forward-reverse-comparison"] },
  { phase: { label: "Beyond the basics", tone: "cyan" }, objective: "Control word, PW status, AC failure, and how VPWS compares.", steps: ["control-word-intro", "control-word-negotiation", "pw-status-intro", "ac-down-experiment", "ac-down-result", "restore-ac", "transport-independence", "traditional-vs-evpn-vpws", "traditional-vs-l3vpn", "vpws-vs-vpls-preview", "mtu-lab-note"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "Everything below the pseudowire looks healthy, yet the PW is down. Find why.", steps: ["troubleshooting-intro", "fault-injection", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that brings the pseudowire back.", steps: ["repair-challenge", "repaired-recompute"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real CE1 → CE2 frame.", steps: ["verify-send", "verify-push", "verify-core", "verify-deliver"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Confirm every piece of the virtual wire you built.", steps: ["engineer-challenge-intro", "engineer-challenge-confirm"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review how targeted LDP, directional labels and two-label forwarding fit together.", steps: ["complete"] },
];

export const VPWS_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "topology-intro": { doingNow: "CE1 – PE1 – P1 – P2 – PE2 – CE2. Only PE1 and PE2 know about the service." },
  "attachment-circuit-intro": { doingNow: "The AC on each PE is ge-0/0/0.100 toward its CE." },
  "vlan-vs-pwid": { takeaway: "VLAN 100 is local to the AC; PW ID 5000 identifies the pseudowire in signaling." },
  "ldp-transport-up": { doingNow: "Control plane: hop-by-hop LDP gives PE1 a transport LSP toward PE2 (P1 label 102, P2 label 203, PE2 implicit-null)." },
  "predict-transport-implies-pw": { doingNow: "Think about what PE2 would need to know about an arriving frame." },
  "pw-still-down": { takeaway: "Transport UP is necessary, not sufficient." },
  "targeted-ldp-intro": { doingNow: "Control plane: PE1 and PE2 peer loopback-to-loopback; P1 and P2 are not part of it." },
  "targeted-hello": { doingNow: "Control plane: unicast targeted Hello from PE1 (1.1.1.1) to PE2." },
  "targeted-tcp": { doingNow: "Control plane: TCP session between the loopbacks. It carries signaling, never customer frames." },
  "targeted-init": { doingNow: "Control plane: LDP Initialization negotiates the session." },
  "targeted-operational": { takeaway: "The session can now carry PW label mappings." },
  "pw-fec-defined": { doingNow: "Both PEs are configured with PW type Ethernet, PW ID 5000." },
  "predict-pwid-is-label": { doingNow: "Re-read the PW ID vs. label step before answering." },
  "pe1-allocates-label": { doingNow: "PE1 picks 24001: the label it wants to RECEIVE for this PW." },
  "pe2-allocates-label": { doingNow: "PE2 picks 25001: the label it wants to RECEIVE for this PW." },
  "label-mapping-pe1-to-pe2": { doingNow: "Control plane: PE1 tells PE2 “send this PW to me with 24001”." },
  "label-mapping-pe2-to-pe1": { doingNow: "Control plane: PE2 tells PE1 “send this PW to me with 25001”.", takeaway: "The receiver owns the label; the sender uses the remote's label." },
  "predict-same-pw-label": { doingNow: "Look at who advertised each label and for which direction." },
  "pw-up": { takeaway: "FEC match, targeted LDP, both labels, transport and both ACs: PW UP." },
  "predict-p-router-pwid": { doingNow: "Think about which label a P router reads." },
  "packet-before-encap": { doingNow: "Data plane: CE1 sends a plain Ethernet frame on the AC." },
  "pe1-push-pw": { doingNow: "Data plane: PE1 pushes PE2's label 25001. It is the only label, so S=1." },
  "pe1-push-transport": { doingNow: "Data plane: PE1 pushes transport label 102 on top (S=0). 25001 keeps S=1." },
  "two-label-stack-signature": { takeaway: "OUTER = transport to PE2. INNER = PW label owned by PE2." },
  "p1-transport-forward": { doingNow: "Data plane: P1 swaps only the outer label, 102 → 203." },
  "p2-transport-forward-php": { doingNow: "Data plane: P2 pops the transport label (PHP). 25001 S=1 remains." },
  "p-router-knowledge-boundary": { takeaway: "P routers never see the PW ID, the AC or a customer MAC." },
  "predict-egress-label": { doingNow: "Recall what PE2 advertised, and to whom." },
  "pe2-pw-lookup": { doingNow: "Data plane: 25001 is PE2's own receive label → CUST-A-VPWS → ge-0/0/0.100." },
  "pe2-deliver": { doingNow: "Data plane: PE2 pops the PW label and delivers the Ethernet frame to CE2." },
  "pe2-push-reverse": { doingNow: "Data plane: PE2 pushes PE1's label 24001 (S=1), then transport 100 (S=0)." },
  "core-reverse-forward": { doingNow: "Data plane: P2 swaps the outer label 100 → 101; 24001 stays S=1." },
  "core-reverse-php": { doingNow: "Data plane: P1 pops the transport label (PHP) toward PE1." },
  "pe1-reverse-lookup-deliver": { doingNow: "Data plane: 24001 is PE1's own receive label → CE1." },
  "forward-reverse-comparison": { takeaway: "CE1→CE2 carries 25001; CE2→CE1 carries 24001." },
  "ac-down-result": { takeaway: "A healthy control session doesn't guarantee a healthy service." },
  "fault-injection": { doingNow: "PE2's pseudowire configuration changed. Transport, targeted LDP and ACs stay up." },
  "diagnostic-ladder": { doingNow: "Walk the ladder: transport, targeted LDP, ACs, then what each PE signals for the PW." },
  "repair-challenge": { doingNow: "Pick the repair that fixes the layer you identified. Wrong choices explain why." },
  "verify-push": { doingNow: "Data plane: PE1 pushes the two labels again." },
  "verify-deliver": { takeaway: "Verified with real traffic, not just a state change." },
};
