import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for EVPN ARP/ND Suppression — presentation only; phase objectives also show on question/repair steps, so they never state an answer or name the fault before its diagnostic stage. */
export const EVPNA_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Baseline ARP", tone: "cyan" }, objective: "Watch what one ARP request costs across the fabric today.", steps: ["intro", "arp-broadcast", "leaf1-classify-bum", "flood-replicate", "flood-delivered", "cost-visible", "predict-at-scale"] },
  { phase: { label: "Already known", tone: "bgp" }, objective: "Check what the ingress VTEP already knows before it floods.", steps: ["type2-recap", "predict-need-to-flood", "suppression-intro", "mac-ip-binding-table"] },
  { phase: { label: "Suppression", tone: "ip" }, objective: "Send the same request with suppression enabled and inspect the reply.", steps: ["suppressed-arp-request", "enter-leaf1-suppression-pipeline", "proxy-reply-built", "accuracy-note", "before-after-comparison", "control-discovery-data-recap"] },
  { phase: { label: "Limits", tone: "warning" }, objective: "Decide what happens when the VTEP does not have a usable answer.", steps: ["unknown-binding-case", "predict-unknown-binding", "unknown-binding-fallback", "stale-binding-warning", "mobility-tie-in"] },
  { phase: { label: "IPv6", tone: "violet" }, objective: "Map the same idea onto IPv6 Neighbor Discovery.", steps: ["nd-intro", "arp-vs-nd-comparison", "predict-type2-dependency", "type2-type3-relationship"] },
  { phase: { label: "Incident", tone: "danger" }, objective: "ARP requests are crossing the fabric again. Find the failing layer.", steps: ["break-intro", "fault-injected", "trouble-intro", "trouble-question", "diagnostic-layers", "visualize-fault"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the fix for the layer you identified, then prove it.", steps: ["repair-challenge", "verify-dataplane"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review Type 2 knowledge, Type 3 fallback and the tables involved.", steps: ["concept-summary", "complete"] },
];

export const EVPNA_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "flood-replicate": { doingNow: "LEAF1 treats the ARP broadcast as BUM and creates one VXLAN copy per flood-list entry." },
  "mac-ip-binding-table": { doingNow: "LEAF1's MAC/IP binding table is a different table from its MAC table and from HOST-A's ARP cache." },
  "proxy-reply-built": { doingNow: "LEAF1 answers from its own binding — the reply is not generated by HOST-B." },
  "accuracy-note": { takeaway: "Suppression changes discovery only; data traffic still crosses the fabric to the real VTEP." },
  "nd-intro": { doingNow: "IPv6 uses Neighbor Solicitation / Neighbor Advertisement — never ARP." },
  "fault-injected": { doingNow: "A controlled, educational fault is injected on one leaf." },
  "trouble-intro": { doingNow: "Connectivity still works eventually; the fabric is doing more work than it should." },
  "repair-challenge": { doingNow: "Choose the change that fixes the cause you identified." },
  "verify-dataplane": { takeaway: "Suppression proven with a real request — zero remote copies." },
};
