import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for SR-MPLS Foundations — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. */
export const SRF_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Steer MPLS traffic with an ordered list of instructions instead of per-LSP signaling.", steps: ["intro", "recap", "predict-sr-eliminates-igp"] },
  { phase: { label: "IGP foundation", tone: "ospf" }, objective: "Watch ordinary IP follow the IGP shortest path before any SR is involved.", steps: ["topology-intro", "predict-igp-forwarding", "send-ip-normal", "ip-r1", "ip-r2", "ip-r4", "ip-r6-deliver"] },
  { phase: { label: "SRGB & SIDs", tone: "violet" }, objective: "Map SID indexes to MPLS labels and see how every router learns them.", steps: ["segment-intro", "srgb-intro", "node-sid-terminology", "sid-database-intro", "control-plane-distribution"] },
  { phase: { label: "Node-SID forwarding", tone: "mpls" }, objective: "Follow one Node SID from R1 to R6, hop by hop.", steps: ["send-node-sid-r6", "r1-push-node-sid", "r2-continue", "r4-pop-php", "r6-deliver-node-sid"] },
  { phase: { label: "Topology change", tone: "warning" }, objective: "Change one IGP metric and observe what the same Node SID does.", steps: ["metric-change-intro", "change-metric", "predict-node-sid-metric-change", "send-node-sid-r6-again", "r1-push-node-sid-2", "r3-continue-2", "r5-pop-php-2", "r6-deliver-node-sid-2", "metric-restore"] },
  { phase: { label: "Steering need", tone: "warning" }, objective: "Operations needs traffic on one particular link.", steps: ["predict-node-sid-force"] },
  { phase: { label: "Adj-SID", tone: "violet" }, objective: "Meet the instruction that names one adjacency.", steps: ["adjsid-intro", "adjsid-local-significance", "predict-adjsid-type", "sid-db-update"] },
  { phase: { label: "Segment list", tone: "mpls" }, objective: "Impose a segment list and compare the logical list with the labels on the wire.", steps: ["build-segment-list-intro", "segment-list-viewer-intro", "send-steered-packet", "r1-push-segments", "r3-node-sid-complete", "r3-execute-adjsid", "r5-continue", "r6-pop-node-sid", "r6-deliver-steered"] },
  { phase: { label: "Concepts", tone: "cyan" }, objective: "Compare SR steering with RSVP-TE and experiment with segment lists.", steps: ["segment-vs-label-stack", "rsvp-vs-sr-comparison", "views-intro", "segment-lab-intro", "lab-compare-experiment"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "A new segment list fails at R1 while everything else is healthy. Find out why.", steps: ["troubleshooting-intro", "predict-r1-interpret-adjsid", "fault-send", "fault-r1-invalid", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that makes the R3→R5 segment list executable.", steps: ["repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the fix by following a real packet end to end.", steps: ["repaired-send", "repaired-r1-push", "repaired-r3-complete", "repaired-r3-adj", "repaired-r5-continue", "repaired-r6-pop", "repaired-r6-deliver"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Program R1 → R3 → R5 → R6 with the right instructions.", steps: ["engineer-challenge"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review Node SIDs, Adj-SIDs, the SRGB and the segment stack.", steps: ["complete"] },
];

export const SRF_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  recap: { takeaway: "SR does not replace the IGP — it adds instructions on top of it." },
  "topology-intro": { doingNow: "Top path R1–R2–R4–R6 costs 30; bottom path R1–R3–R5–R6 costs 45." },
  "predict-igp-forwarding": { doingNow: "Think about what every router consults for plain IP." },
  "ip-r6-deliver": { takeaway: "Plain IP followed the IGP shortest path, cost 30." },
  "srgb-intro": { doingNow: "Control plane: SRGB 16000–23999 everywhere; indexes R1=1 … R6=6." },
  "node-sid-terminology": { doingNow: "R6's index 6 → label 16006 (16000 + 6).", takeaway: "A Node SID is the Prefix-SID of a router's own loopback." },
  "sid-database-intro": { takeaway: "Node SIDs are global in the SR domain; ordinary Adj-SIDs are local to their owner." },
  "control-plane-distribution": { doingNow: "Control plane: the IGP's SR extensions carry Prefix-SID and Adj-SID advertisements." },
  "r1-push-node-sid": { doingNow: "Data plane: R1 pushes 16006 S1 — one label, the bottom of the stack." },
  "r2-continue": { doingNow: "Data plane: R2 forwards 16006 unchanged toward R4, its own shortest-path next hop." },
  "r4-pop-php": { doingNow: "Data plane: R4 is penultimate for R6 (implicit-null) and pops 16006.", takeaway: "R4 → R6 carries plain IP." },
  "r6-deliver-node-sid": { takeaway: "A Node SID means \"reach R6 by the current shortest path\" — here R1 → R2 → R4 → R6." },
  "change-metric": { doingNow: "Control plane: R2-R4 goes 10 → 50; the top path now costs 70, the bottom path 45." },
  "predict-node-sid-metric-change": { doingNow: "The SID is unchanged — think about what decides the path it follows." },
  "r1-push-node-sid-2": { doingNow: "Data plane: the same label, 16006 S1." },
  "r5-pop-php-2": { doingNow: "Data plane: R5 is now penultimate and pops 16006 (PHP)." },
  "r6-deliver-node-sid-2": { takeaway: "Same Node SID, different IGP shortest path, different physical path." },
  "predict-node-sid-force": { doingNow: "Recall exactly what a Node SID instructs a transit router to do." },
  "adjsid-intro": { doingNow: "Control plane: R3 advertises Adj-SID 24035 for its R3→R5 adjacency." },
  "adjsid-local-significance": { takeaway: "24035 is executable only at R3, its owner." },
  "predict-adjsid-type": { doingNow: "Compare what each SID type promises." },
  "sid-db-update": { doingNow: "16006 and 16003 are global Node SIDs; 24035 is R3's local Adj-SID." },
  "segment-list-viewer-intro": { takeaway: "The segment list is logical: the active instruction first, the rest pending." },
  "send-steered-packet": { doingNow: "Logical list 16003 → 24035 → 16006. R1 is R3's penultimate hop, so 16003 is completed by PHP at R1." },
  "r1-push-segments": { doingNow: "Wire stack R1 → R3: 24035 S0 over 16006 S1 — 16003 is not on the wire.", takeaway: "Logical list ≠ wire stack when PHP applies." },
  "r3-node-sid-complete": { doingNow: "No pop at R3: segment 1 already completed by PHP; 24035 is now on top." },
  "r3-execute-adjsid": { doingNow: "Data plane: R3 executes its own 24035, pops it, and sends 16006 S1 over R3→R5." },
  "r5-continue": { doingNow: "Data plane: R5 is penultimate for R6 and pops 16006 (PHP).", takeaway: "R5 → R6 carries plain IP." },
  "r6-pop-node-sid": { takeaway: "R6 receives plain IP — it never pops 16006 itself." },
  "r6-deliver-steered": { takeaway: "R3→R5 was used although it is not on the IGP shortest path." },
  "lab-compare-experiment": { takeaway: "Only an Adj-SID pins a specific link; a Node SID follows the shortest path." },
  "troubleshooting-intro": { doingNow: "IP, IGP and R6 Node-SID forwarding are all healthy." },
  "predict-r1-interpret-adjsid": { doingNow: "Think about which router can execute a local Adj-SID." },
  "fault-r1-invalid": { doingNow: "Data plane: the packet is dropped at R1 before any label is imposed." },
  "diagnostic-ladder": { doingNow: "Walk the layers from physical up to segment execution." },
  "repair-challenge": { doingNow: "Pick the change that makes every SID executable where it becomes active." },
  "repaired-r1-push": { doingNow: "Wire stack R1 → R3: 24035 S0 over 16006 S1." },
  "repaired-r3-adj": { doingNow: "R3 executes 24035; R3 → R5 carries 16006 S1." },
  "repaired-r5-continue": { doingNow: "R5 pops 16006 (PHP); R5 → R6 carries plain IP." },
  "repaired-r6-deliver": { takeaway: "Fix verified with a real packet over R3→R5." },
  "engineer-challenge": { doingNow: "Use what you proved: ordering and ownership of each instruction." },
};
