import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for SRv6 Endpoint Behaviors — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/challenge steps, so they never state an answer. */
export const SRV6E_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Explore why SRv6 defines more than one endpoint behavior.", steps: ["intro", "central-answer", "behavior-mental-model", "predict-why-many-behaviors"] },
  { phase: { label: "Taxonomy", tone: "violet" }, objective: "Sort the behaviors into families and learn the naming.", steps: ["taxonomy-intro", "mnemonic"] },
  { phase: { label: "SID tables", tone: "ip" }, objective: "Program R3 and R6 with several SIDs under one locator each.", steps: ["topology-extended", "predict-normal-r3-r6", "sid-allocation-r3", "sid-allocation-r6", "richer-local-sid-table", "predict-two-sids-different-behaviors"] },
  { phase: { label: "End vs End.X", tone: "warning" }, objective: "Send the same next segment through End and then End.X, and compare.", steps: ["end-recap", "predict-endx-rewrites-da", "policy-a-intro", "policy-a-classify", "policy-a-transit", "policy-a-r3-end", "policy-a-r3-forward", "policy-a-deliver", "policy-b-intro", "policy-b-classify-transit", "policy-b-r3-endx", "policy-b-r3-forward-adjacency", "policy-b-r4-r5-transit", "policy-b-deliver", "signature-end-vs-endx", "endx-accuracy-note", "endx-adjsid-analogy"] },
  { phase: { label: "End.T", tone: "ospf" }, objective: "Send the same next segment through End.T and see which table it uses.", steps: ["endt-intro", "predict-endt-decapsulates", "policy-c-intro", "policy-c-transit", "policy-c-r3-endt", "policy-c-core-b-lookup", "policy-c-r4-r5-transit", "policy-c-deliver", "end-vs-endt-comparison", "endt-vs-dt6-distinction"] },
  { phase: { label: "Decap family", tone: "violet" }, objective: "Meet the service behaviors and the rule they all share.", steps: ["decap-family-transition", "outer-inner-packet-model", "headend-encaps-note", "final-segment-rule", "final-segment-invalid-demo", "final-segment-invalid-result"] },
  { phase: { label: "DX6 / DX4", tone: "ip" }, objective: "Cross-connect exposed traffic to a fixed neighbor.", steps: ["dx6-intro", "dx6-encaps-transit", "dx6-r6-match", "dx6-deliver", "dx4-intro", "dx4-transit", "dx4-r6-match-deliver", "dx-analogy", "dx-vs-dt-visual"] },
  { phase: { label: "DT6 / DT4", tone: "bgp" }, objective: "Look exposed traffic up in a tenant table.", steps: ["dt6-intro", "dt6-transit", "dt6-r6-deliver", "dt4-intro", "dt4-send-a", "dt4-a-transit-deliver", "dt4-send-b", "dt4-b-transit-deliver", "per-ce-vs-per-vrf"] },
  { phase: { label: "DX2", tone: "ethernet" }, objective: "Carry an Ethernet frame and cross-connect it at R6.", steps: ["dx2-intro", "dx2-transit", "dx2-r6-execute", "dx2-deliver", "dx2-advanced-preview"] },
  { phase: { label: "Catalog", tone: "violet" }, objective: "Compare every behavior side by side and preview the rest.", steps: ["behavior-comparison-intro", "endpoint-flavors-preview", "dt46-and-others-preview"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "Traffic for 10.10.2.8 decapsulates at R6 but misses CE4-B. Find out why.", steps: ["troubleshooting-intro", "predict-fault-hypothesis", "diagnostic-ladder", "fault-inject", "fault-send", "fault-transit-healthy", "fault-wrong-delivery", "final-segment-dt4-experiment"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores the intended delivery.", steps: ["repair-challenge", "repair-applied"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real resend.", steps: ["repaired-resend", "repaired-transit", "repaired-deliver"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Match each requirement to the endpoint behavior it needs.", steps: ["program-the-endpoint", "challenge-verified", "engineer-challenge-complete"] },
  { phase: { label: "Complete", tone: "success" }, objective: "The SID reaches an instruction; the behavior defines it.", steps: ["complete"] },
];

export const SRV6E_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "topology-extended": { doingNow: "Topology: new R3-R4 link (metric 20); R3's shortest path to R6 is still direct." },
  "sid-allocation-r3": { doingNow: "R3: End 0x1, End.X 0x2 → R4, End.T 0x3 → CORE-B — one locator." },
  "sid-allocation-r6": { doingNow: "R6: End plus DX6 → CE6, DX4 → CE4-A, DT6 → VRF-CUST6, DT4 → VRF-CUST4, DX2 → ge-0/0/7." },
  "policy-a-classify": { doingNow: "DA = R3 End SID; SRH SL 1 / LE 1 with [0] R6 End · [1] R3 End." },
  "policy-a-r3-end": { doingNow: "End at R3: SL 1 → 0, DA ← R6 End SID." },
  "policy-a-r3-forward": { doingNow: "Ordinary FIB lookup on the new DA: R3 → R6 directly." },
  "policy-a-deliver": { takeaway: "End: R1 → R2 → R3 → R6." },
  "policy-b-classify-transit": { doingNow: "DA = R3 End.X SID — to R1 and R2 it is just R3's locator." },
  "policy-b-r3-endx": { doingNow: "End.X at R3: SL 1 → 0, DA ← R6 End SID — the DA is not R4's address." },
  "policy-b-r3-forward-adjacency": { doingNow: "End.X forces the bound adjacency R3 → R4, not the FIB." },
  "policy-b-r4-r5-transit": { doingNow: "R4 and R5 are plain IPv6 transit toward R6." },
  "policy-b-deliver": { takeaway: "Same next segment, different path: R1 → R2 → R3 → R4 → R5 → R6." },
  "policy-c-r3-endt": { doingNow: "End.T at R3: SL 1 → 0, DA ← R6 End SID; the next lookup uses CORE-B." },
  "policy-c-core-b-lookup": { doingNow: "CORE-B has no R3-R6 link, so R6's locator resolves via R4." },
  "policy-c-deliver": { takeaway: "Same DA as End, different table, different next hop." },
  "final-segment-invalid-demo": { doingNow: "Deliberately wrong order ⟨R6 End.DT4, R3 End⟩: DT4 becomes active with SL 1." },
  "final-segment-invalid-result": { doingNow: "SL is 1, not 0 → INVALID_FINAL_SEGMENT: no decap, packet dropped." },
  "dx6-encaps-transit": { doingNow: "Outer DA = R6 End.DX6 SID, no SRH (single segment); the inner IPv6 packet rides untouched." },
  "dx6-r6-match": { doingNow: "R6 matches End.DX6; final-segment and payload checks pass." },
  "dx6-deliver": { doingNow: "Shown: the packet at R6 before End.DX6 decap; the inner IPv6 packet goes to CE6.", takeaway: "DX6: no tenant lookup — the SID picked the neighbor." },
  "dx4-transit": { doingNow: "Outer DA = R6 End.DX4 SID; inner IPv4 10.10.1.5." },
  "dx4-r6-match-deliver": { doingNow: "Shown: before End.DX4 decap; the inner IPv4 packet is cross-connected to CE4-A." },
  "dt6-r6-deliver": { doingNow: "Shown: before End.DT6 decap; the exposed IPv6 packet is looked up in VRF-CUST6." },
  "dt4-a-transit-deliver": { doingNow: "Shown: before End.DT4 decap; VRF-CUST4 sends 10.10.1.5 to CE4-A." },
  "dt4-b-transit-deliver": { doingNow: "Shown: same DT4 SID before decap; VRF-CUST4 sends 10.10.2.8 to CE4-B.", takeaway: "One DT4 SID, two CEs — the inner destination decides." },
  "dx2-transit": { doingNow: "Outer DA = R6 End.DX2 SID; the Ethernet frame is invisible to transit routers." },
  "dx2-deliver": { doingNow: "Shown: before End.DX2 decap; the frame leaves ge-0/0/7 with no MAC lookup." },
  "troubleshooting-intro": { doingNow: "Service SID installed, decap succeeds — yet 10.10.2.8 never reaches CE4-B." },
  "fault-inject": { doingNow: "Local SID state: the same SID value is now bound as End.DX4 → CE4-A." },
  "fault-transit-healthy": { doingNow: "Encapsulation, IGP forwarding and locator reachability are all healthy." },
  "fault-wrong-delivery": { doingNow: "Shown: before the misbound End.DX4 decap; 10.10.2.8 will go to CE4-A, and VRF-CUST4 is never consulted." },
  "repair-challenge": { doingNow: "Choose the change that restores the intended delivery." },
  "repair-applied": { doingNow: "Local SID state: the SID value is unchanged; only its binding changes." },
  "repaired-deliver": { doingNow: "Shown: before the restored End.DT4 decap; VRF-CUST4 sends 10.10.2.8 to CE4-B.", takeaway: "Repair verified with a real resend." },
  "program-the-endpoint": { doingNow: "Every requirement was already proven by a real packet earlier in this lesson." },
};
