import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the SR TI-LFA lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. This lesson models no PHP. */
export const TILFA_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Repair SR traffic locally, without the headend and without a pre-signaled bypass.", steps: ["intro", "recap-known", "rsvp-frr-recap", "ti-lfa-preview", "protection-object-distinction", "name-explain", "name-caution"] },
  { phase: { label: "Primary path", tone: "ospf" }, objective: "Establish the primary path before protecting anything.", steps: ["topology-intro", "predict-shortest-path", "node-sid-recap", "send-normal-1", "r1-push-normal", "r2-swap-normal", "r4-swap-normal", "r6-deliver-normal"] },
  { phase: { label: "Protection goal", tone: "warning" }, objective: "Choose the resource to protect and the router responsible for it.", steps: ["protected-resource-intro", "predict-plr"] },
  { phase: { label: "No protection", tone: "danger" }, objective: "See what a failure costs when nothing is precomputed.", steps: ["no-tilfa-intro", "fail-no-protection", "no-backup-interruption", "normal-recovery-concept", "restore-for-tilfa"] },
  { phase: { label: "P / Q spaces", tone: "violet" }, objective: "Derive the post-convergence path, P-Space, Q-Space and the repair point.", steps: ["post-convergence-intro", "post-convergence-compute", "p-space-intro", "p-space-compute", "q-space-intro", "q-space-compute", "pq-intersection", "pq-select", "classic-lfa-note", "remote-lfa-note"] },
  { phase: { label: "Repair calculation", tone: "mpls" }, objective: "Encode the repair as a minimal SR segment list.", steps: ["repair-list-intro", "repair-list-compute", "precompute-pipeline"] },
  { phase: { label: "Repair ready", tone: "success" }, objective: "Check what READY protection means for live traffic.", steps: ["protection-ready", "predict-ready-means-active", "failure-detection-note", "send-normal-2", "r1-push-normal-2", "r2-forward-normal-2"] },
  { phase: { label: "Local repair", tone: "danger" }, objective: "Fail R2-R4 and follow the locally repaired packet.", steps: ["trigger-failure", "r2-detects-failure", "repair-activate", "repair-label-stack", "r2-xray-pipeline", "r3-transit-normal", "repair-completes-r5", "predict-repair-completes", "r5-to-r6", "destination-reached", "repaired-path-highlight"] },
  { phase: { label: "Convergence", tone: "cyan" }, objective: "Separate local repair from global IGP convergence.", steps: ["local-vs-global", "global-convergence-compute", "post-convergence-forwarding", "repair-temporary", "recovery-timeline", "protection-lifecycle-recap", "restore-after-link-demo"] },
  { phase: { label: "Node protection", tone: "violet" }, objective: "Protect R4 as a whole node, not just one link.", steps: ["node-protection-intro", "node-protection-compute", "protection-comparison", "multi-sid-example"] },
  { phase: { label: "Comparisons", tone: "cyan" }, objective: "Place TI-LFA next to classic LFA, RSVP FRR and SR Policy.", steps: ["classic-lfa-vs-tilfa", "rsvp-frr-vs-tilfa", "sr-policy-interaction", "predict-sr-policy-vs-tilfa"] },
  { phase: { label: "Protection limits", tone: "warning" }, objective: "Break the repair path itself and see what protection reports.", steps: ["repair-path-failure-experiment", "protection-unavailable-primary-up", "restore-repair-path", "no-repair-path-scenario", "restore-all"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "Protection showed READY, yet local repair failed. Find out why.", steps: ["troubleshooting-intro", "incident-narrative", "fail-for-incident", "stale-repair-fails", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that makes local repair valid again.", steps: ["repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Fail R2-R4 again and prove the repaired protection with a real packet.", steps: ["repaired-restore", "verify-trigger-fail", "verify-push", "verify-repair", "verify-deliver"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Confirm link and node protection end to end.", steps: ["engineer-challenge-intro", "engineer-challenge-confirm"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review P/Q spaces, repair lists, local repair and recomputation.", steps: ["complete"] },
];

export const TILFA_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "topology-intro": { doingNow: "Links: R1-R2, R2-R4, R4-R6 = 10; R2-R3, R3-R5, R5-R6 = 15." },
  "predict-shortest-path": { doingNow: "Add up each candidate path's metrics." },
  "node-sid-recap": { doingNow: "R6's Node SID: 16000 + 6 = 16006." },
  "r1-push-normal": { doingNow: "Data plane: R1 pushes 16006 S1." },
  "r6-deliver-normal": { takeaway: "This lesson models no PHP: R6 receives 16006 and completes it." },
  "protected-resource-intro": { doingNow: "Protected resource: the R2-R4 link." },
  "predict-plr": { doingNow: "Think about which router first notices the link is gone." },
  "no-backup-interruption": { takeaway: "Without precomputation, traffic waits for global convergence." },
  "post-convergence-intro": { takeaway: "The post-convergence path is R2's shortest path with R2-R4 removed." },
  "p-space-compute": { doingNow: "Computed from R2: P-Space = {R1, R3, R5}." },
  "q-space-compute": { doingNow: "Computed toward R6: Q-Space = {R3, R4, R5}." },
  "pq-select": { doingNow: "PQ candidates R3 and R5; the one closest to the destination, R5, is selected." },
  "repair-list-compute": { doingNow: "R2's own shortest path to R5 is R2 → R3 → R5, so one Node SID (16005) suffices." },
  "protection-ready": { doingNow: "Repair list: R5's Node SID 16005 goes on top of R6's 16006." },
  "predict-ready-means-active": { doingNow: "Separate \"precomputed and installed\" from \"carrying traffic\"." },
  "r1-push-normal-2": { doingNow: "Data plane: R1 pushes 16006 S1 — R1 knows nothing about the repair." },
  "trigger-failure": { doingNow: "Topology: R2-R4 goes down." },
  "repair-activate": { doingNow: "R2 pushes the precomputed repair — no new computation happens now." },
  "repair-label-stack": { doingNow: "Wire stack R2 → R3: 16005 S0 (R5 Node SID, repair) over 16006 S1 (R6 Node SID, original).", takeaway: "The original instruction survives underneath the repair SID." },
  "r3-transit-normal": { doingNow: "The active SID is R5's 16005 — R3 is ordinary transit and forwards it toward R5 unchanged." },
  "repair-completes-r5": { doingNow: "R5 is the target of 16005 and completes it; 16006 S1 is now on top." },
  "predict-repair-completes": { doingNow: "Look at what was underneath the repair SID." },
  "r5-to-r6": { doingNow: "Data plane: R5 forwards 16006 S1 to R6 over the direct link." },
  "destination-reached": { takeaway: "Local repair covered R2 → R3 → R5; the rest was ordinary forwarding." },
  "post-convergence-forwarding": { takeaway: "After convergence R1's stack is just 16006 again — no repair label." },
  "node-protection-compute": { doingNow: "P/Q recomputed with R4 excluded as a whole node." },
  "multi-sid-example": { takeaway: "A repair list can need more than one SID — here a Node SID plus an Adj-SID." },
  "predict-sr-policy-vs-tilfa": { doingNow: "Consider where and when each mechanism acts." },
  "protection-unavailable-primary-up": { takeaway: "PRIMARY UP and PROTECTION UNAVAILABLE can be true at the same time." },
  "troubleshooting-intro": { doingNow: "Control plane: R2-R3 metric 15 → 25. The primary path doesn't use R2-R3." },
  "stale-repair-fails": { doingNow: "Data plane: R2 pushes the old repair 16005 S0 over 16006 S1 — and it does not reach the post-convergence path." },
  "diagnostic-ladder": { doingNow: "Compare the installed repair with the topology it was computed from." },
  "repair-challenge": { doingNow: "Pick the change that addresses the root cause you found, not a symptom." },
  "verify-push": { doingNow: "Data plane: R1 → R2 carries 16006 S1." },
  "verify-repair": { doingNow: "Wire stack R2 → R3: 16003 S0 (R3 Node SID, repair) over 16006 S1." },
  "verify-deliver": { takeaway: "R3 completes the repair SID; the packet reaches R6 via R5." },
};
