import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for SRv6 Foundations — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. */
export const SRV6F_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Compare how SR-MPLS and SRv6 represent the active segment.", steps: ["intro", "recap-sr-mpls", "predict-srv6-is-mpls-in-ipv6", "srv6-intro", "signature-sr-mpls-vs-srv6"] },
  { phase: { label: "SID anatomy", tone: "violet" }, objective: "Take an SRv6 SID apart: locator, function and argument.", steps: ["what-is-a-sid", "predict-q1-every-address-is-sid", "sid-structure-intro", "sid-layout-domain", "sid-layout-lengths", "build-r3-sid", "build-r6-sid", "arg-treatment"] },
  { phase: { label: "Locator vs SID", tone: "ip" }, objective: "Examine how a locator route relates to a local SID entry.", steps: ["locator-is-routable", "predict-q6-locator-vs-local-sid", "locator-vs-local-sid"] },
  { phase: { label: "Underlay", tone: "ospf" }, objective: "Map the IPv6 underlay every SRv6 packet rides on.", steps: ["topology-intro", "predict-igp-shortest-default", "underlay-first", "locator-fib-r1", "transit-node-requirement"] },
  { phase: { label: "Local SID Table", tone: "violet" }, objective: "Program R3, R5 and R6 with their End SIDs.", steps: ["local-sid-table-intro", "sid-db-vs-fib"] },
  { phase: { label: "Single SID", tone: "ip" }, objective: "Send one packet toward R6's End SID and read every header it carries.", steps: ["single-sid-intro", "predict-q5-single-sid-no-srh", "send-single-sid", "r1-single-fib", "r4-single-transit", "r5-single-transit", "r6-single-local-match-deliver", "single-sid-recap"] },
  { phase: { label: "Segment list", tone: "warning" }, objective: "Encode the program ⟨R3, R6⟩ into a real Segment Routing Header.", steps: ["multi-sid-need", "high-level-order-intro", "predict-q3-segment-list-0", "srh-reversed-encoding", "full-srh-mode-note", "srh-viewer-intro", "predict-q2-active-segment-location", "active-segment-rule"] },
  { phase: { label: "Data plane", tone: "ip" }, objective: "Follow ⟨R3, R6⟩ hop by hop and note who touches the SRH.", steps: ["initial-packet-r1", "r1-forwards-toward-r3", "predict-q4-transit-decrements-sl", "r2-transit", "r3-local-sid-match", "r3-end-execute", "r3-r6-forward", "r6-final-end", "r6-deliver-multi"] },
  { phase: { label: "Locators", tone: "ospf" }, objective: "Change the IGP under an unchanged SID and observe the result.", steps: ["local-sid-table-is-programming", "locator-aggregation-demo", "locator-experiment-intro", "locator-experiment-change-metric", "locator-experiment-resend", "locator-experiment-r1-r2-r3-r6", "predict-q9-path-can-change", "locator-experiment-restore", "sid-vs-locator-comparison"] },
  { phase: { label: "SRv6 vs SR-MPLS", tone: "cyan" }, objective: "Pin down what SRv6 does and does not borrow from SR-MPLS.", steps: ["sr-mpls-node-sid-comparison", "no-srgb", "no-mpls-ops", "srh-field-explanation", "predict-q7-end-is-label-swap", "segments-left-distinction", "predict-q8-sl-counts-hops"] },
  { phase: { label: "Three segments", tone: "warning" }, objective: "Run the three-segment program ⟨R3, R5, R6⟩.", steps: ["three-sid-demo-intro", "three-sid-r1-r2-r3", "three-sid-r3-end", "three-sid-r3-r6", "three-sid-r6-transit", "three-sid-r5-end", "three-sid-r5-r6", "three-sid-r6-final"] },
  { phase: { label: "Beyond End", tone: "violet" }, objective: "Preview other behaviors and explore the views and the segment lab.", steps: ["end-x-preview", "service-behavior-preview-table", "views-intro", "physical-ipv6-srv6-views-intro", "sr-mpls-vs-srv6-full-comparison", "segment-lab-intro"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "The ⟨R3, R6⟩ program stops at R3. Find out why.", steps: ["troubleshooting-intro", "predict-fault-hypothesis", "diagnostic-ladder", "fault-inject", "fault-send", "fault-r1-r2-healthy", "fault-r3-missing-sid-drop"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that addresses the cause you isolated.", steps: ["repair-challenge", "repair-applied"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real resend.", steps: ["repaired-send", "repaired-r1-r2", "repaired-r3-end", "repaired-r3-r6", "repaired-r6-final", "repaired-deliver"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review SIDs, locators, the SRH and End.", steps: ["engineer-challenge", "complete"] },
];

export const SRV6F_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "build-r3-sid": { doingNow: "Locator 2001:db8:100:3::/64 + function 0x1 → R3 End SID 2001:db8:100:3:1::." },
  "build-r6-sid": { doingNow: "Locator 2001:db8:100:6::/64 + function 0x1 → R6 End SID 2001:db8:100:6:1::." },
  "locator-fib-r1": { takeaway: "One FIB route per locator prefix, never one per SID." },
  "local-sid-table-intro": { doingNow: "Local SID state: R3, R5 and R6 each instantiate one End SID." },
  "send-single-sid": { doingNow: "Data plane: DA = R6 End SID 2001:db8:100:6:1::, and there is no SRH." },
  "r1-single-fib": { doingNow: "R1 has no local match — ordinary FIB lookup toward R6's locator, next hop R4." },
  "r4-single-transit": { doingNow: "R4 is plain IPv6 transit: DA unchanged." },
  "r5-single-transit": { doingNow: "R5 owns an End SID, but not this one — plain transit." },
  "r6-single-local-match-deliver": { takeaway: "One SID, no SRH: the IPv6 DA carried the whole program." },
  "srh-reversed-encoding": { doingNow: "Storage is reversed: Segment List[0] = R6 (final), [1] = R3 (first); SL 1, LE 1." },
  "initial-packet-r1": { doingNow: "DA = R3 End SID; SRH SL 1 / LE 1 with [0] R6 · [1] R3." },
  "r1-forwards-toward-r3": { doingNow: "R1 → R2: ordinary IPv6 forwarding toward R3's locator." },
  "r2-transit": { doingNow: "R2 is transit: DA, SL and the Segment List are all unchanged." },
  "r3-local-sid-match": { doingNow: "R3's Local SID Table matches its own End SID." },
  "r3-end-execute": { doingNow: "End at R3: SL 1 → 0, DA ← Segment List[0] = R6 End SID." },
  "r3-r6-forward": { doingNow: "R3 → R6 by an ordinary FIB lookup on the new DA." },
  "r6-final-end": { doingNow: "SL is already 0 — final End; R6 never decrements below zero." },
  "r6-deliver-multi": { takeaway: "Two segments, three physical hops: R1 → R2 → R3 → R6." },
  "locator-experiment-change-metric": { doingNow: "Topology: the R4-R5 metric rises, so the bottom path is no longer shortest." },
  "locator-experiment-restore": { doingNow: "Topology: R4-R5 back to 5 — the bottom path wins again." },
  "three-sid-demo-intro": { doingNow: "SRH SL 2 / LE 2 with [0] R6 · [1] R5 · [2] R3; DA = R3 End SID." },
  "three-sid-r3-end": { doingNow: "End at R3: SL 2 → 1, DA ← Segment List[1] = R5 End SID. The list itself never changes." },
  "three-sid-r3-r6": { doingNow: "R3's shortest path toward R5's locator runs through R6." },
  "three-sid-r6-transit": { doingNow: "R6 is transit here: the DA is R5's SID, so SL stays 1." },
  "three-sid-r5-end": { doingNow: "End at R5: SL 1 → 0, DA ← Segment List[0] = R6 End SID." },
  "three-sid-r6-final": { takeaway: "Three segments, five physical hops — SL counts segments, not hops." },
  "troubleshooting-intro": { doingNow: "R3's locator is reachable and the packet reaches R3, yet the program never advances." },
  "fault-inject": { doingNow: "Local SID state: R3's End SID entry has been removed." },
  "fault-r3-missing-sid-drop": { doingNow: "R3 has no local SID entry for this DA — the packet is dropped." },
  "repair-challenge": { doingNow: "Choose the change that fixes the cause you identified." },
  "repaired-r3-end": { doingNow: "End at R3 again: SL 1 → 0, DA ← R6 End SID." },
  "repaired-deliver": { takeaway: "Repair verified with a real resend over R1 → R2 → R3 → R6." },
};
