import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for SRv6 TI-LFA — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. */
export const SRV6T_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Find out what the PLR can do the moment a protected link fails.", steps: ["intro", "predict-plr-wait", "terminology-plr", "ti-accuracy", "predict-ti-meaning"] },
  { phase: { label: "Topology", tone: "ospf" }, objective: "Map the primary path, the protection topology and P3's current route.", steps: ["topology-intro", "metrics-recap", "predict-shortest-path", "p3-pre-failure-route", "predict-p3-route"] },
  { phase: { label: "Naive reroute", tone: "danger" }, objective: "Watch what happens if P1 simply redirects the original packet.", steps: ["naive-fail-injected", "naive-forward-p1-p3", "naive-p3-stale-fib", "naive-loop-p3-p1", "predict-naive-loop", "naive-loop-explained"] },
  { phase: { label: "Convergence model", tone: "ospf" }, objective: "Separate pre-convergence forwarding from the post-convergence path.", steps: ["restore-for-tilfa", "post-convergence-intro", "post-convergence-compute", "phases-intro", "precompute-intro"] },
  { phase: { label: "Repair anatomy", tone: "violet" }, objective: "Take the repair apart: outgoing interface plus repair program.", steps: ["repair-anatomy-intro", "why-p4-endx", "globally-routed-adjacency", "usd-intro", "predict-usd", "baseline-packet-intro"] },
  { phase: { label: "P / Q spaces", tone: "warning" }, objective: "Compute P-Space, Extended P-Space and Q-Space from the real topology.", steps: ["p-space-intro", "p-space-compute", "extended-p-space-intro", "extended-p-space-compute", "q-space-intro", "q-space-compute"] },
  { phase: { label: "Repair program", tone: "violet" }, objective: "Select the repair node and derive the repair program.", steps: ["select-repair-node", "repair-list-derive", "h-encaps-intro", "predict-no-srh", "protection-ready"] },
  { phase: { label: "Activation", tone: "danger" }, objective: "Fail P1-P2 and follow the repaired packet to PE2.", steps: ["trigger-failure", "p1-detects", "p1-activates-repair", "p1-encaps-packet", "p3-transit-repair", "predict-p-routers", "p4-endx-usd-execute", "p4-usd-decap", "p2-normal-forward", "pe2-delivers", "loop-free-recap"] },
  { phase: { label: "Convergence", tone: "success" }, objective: "Hand the traffic back to converged forwarding.", steps: ["igp-converging", "plr-converged", "repair-released", "post-convergence-forwarding"] },
  { phase: { label: "Node protection", tone: "warning" }, objective: "Protect against losing P2 itself, and compare with link protection.", steps: ["node-protection-intro", "node-protection-compute", "node-protection-repair-list", "predict-node-vs-link", "protection-comparison", "srlg-preview"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "Protection activates, yet traffic never reaches PE2. Find out why.", steps: ["break-intro-ti-lfa", "inject-wrong-repair", "incident-tilfa", "fail-for-incident", "wrong-repair-forwards", "wrong-repair-p3-stale", "wrong-repair-loop", "diagnostic-ladder-ti-lfa", "predict-loop-usable"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Rule out the tempting fixes, then apply the one that addresses the cause.", steps: ["wrong-repair-1", "wrong-repair-2", "wrong-repair-3", "repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real resend while the stale FIB is still modeled.", steps: ["verify-resend", "usd-execution-recap"] },
  { phase: { label: "Boundaries", tone: "cyan" }, objective: "Place TI-LFA next to convergence, micro-loops and SR Policy.", steps: ["endpoint-plr-experiment", "tilfa-vs-convergence", "tilfa-vs-microloop", "tilfa-vs-sr-policy", "predict-sr-policy-guarantee", "sr-policy-caveat-experiment", "flex-algo-preview", "sr-mpls-vs-srv6-comparison"] },
  { phase: { label: "Repair size", tone: "violet" }, objective: "Compare the single-SID repair with a real multi-SID SRH.", steps: ["repair-size-lab", "multi-sid-example", "no-fake-srh-contrast"] },
  { phase: { label: "Nested L3VPN", tone: "bgp" }, objective: "Protect an SRv6 L3VPN packet without touching its service outer.", steps: ["l3vpn-integration-intro", "l3vpn-fail-and-repair", "l3vpn-p4-decap-repair-only", "l3vpn-result"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Confirm every piece of the protection design.", steps: ["engineer-challenge-intro", "complete"] },
];

export const SRV6T_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "terminology-plr": { doingNow: "PLR = P1 · protected resource = link P1-P2 · destination = PE2." },
  "metrics-recap": { doingNow: "Primary PE1-P1-P2-PE2 costs 30; the P3/P4 side is the protection topology." },
  "naive-fail-injected": { doingNow: "P1 knows about the failure; P3 and P4 do not yet." },
  "naive-forward-p1-p3": { doingNow: "Data plane: the unmodified packet (DA = PE2) goes to P3." },
  "naive-p3-stale-fib": { doingNow: "P3's stale FIB still points to P1 for PE2." },
  "naive-loop-p3-p1": { takeaway: "P1 → P3 → P1 … a loop built from real per-router FIB state." },
  "post-convergence-compute": { doingNow: "Post-convergence path P1 → P3 → P4 → P2 → PE2 (P1-P2 removed from the graph)." },
  "repair-anatomy-intro": { doingNow: "Repair = outgoing interface P1→P3 + repair program <P4 End.X+USD → P2>." },
  "baseline-packet-intro": { doingNow: "Plain PE1 → PE2 IPv6, no SRH." },
  "p-space-compute": { doingNow: "P-Space(P1) is derived from P1's own pre-convergence shortest paths." },
  "q-space-compute": { doingNow: "Q-Space(PE2): only nodes whose current path to PE2 avoids P1-P2." },
  "select-repair-node": { doingNow: "PacketVerse's documented strategy picks the last P-Space node on the post-convergence path." },
  "repair-list-derive": { doingNow: "One globally routed End.X+USD SID at P4; no separate P4 End first." },
  "protection-ready": { takeaway: "READY means precomputed and installed, not carrying traffic." },
  "trigger-failure": { doingNow: "P1-P2 is down. P1 knows; P3 and P4 still have stale FIBs." },
  "p1-encaps-packet": { doingNow: "Repair outer: SA = P1, DA = P4 End.X+USD, no SRH; the original PE1 packet is untouched inside." },
  "p3-transit-repair": { doingNow: "P3 forwards on P4's locator — it needs no TI-LFA knowledge." },
  "p4-endx-usd-execute": { doingNow: "P4's Local SID Table: End.X, flavor USD, adjacency P2." },
  "p4-usd-decap": { doingNow: "USD removed the whole repair outer; the original packet is forced onto P4→P2." },
  "pe2-delivers": { takeaway: "Delivered via local repair: PE1 → P1 → P3 → P4 → P2 → PE2." },
  "repair-released": { takeaway: "TI-LFA is temporary: the repair outer is no longer applied after convergence." },
  "post-convergence-forwarding": { doingNow: "Final hop to PE2 on ordinary converged forwarding — no repair outer." },
  "node-protection-compute": { doingNow: "P2 excluded entirely: the repair merges at PE2 via P4's direct link." },
  "incident-tilfa": { doingNow: "Detection, backup entry and every alternate link are healthy — delivery still fails." },
  "wrong-repair-forwards": { doingNow: "Same outgoing interface P1→P3, different repair instruction." },
  "wrong-repair-loop": { takeaway: "The loop comes from P3's real stale FIB, not from a scripted flag." },
  "repair-challenge": { doingNow: "Choose the change that fixes the cause you identified." },
  "verify-resend": { doingNow: "Shown: the final verified packet at PE2 after the repair outer was removed; the journey records the full repair path.", takeaway: "Repair proven with a real resend, not just recomputation." },
  "multi-sid-example": { doingNow: "Two repair SIDs need a real SRH: DA = S1, [0] = S2, [1] = S1, SL 1, LE 1." },
  "l3vpn-fail-and-repair": { doingNow: "Repair outer (SA = P1) → SRv6 L3VPN outer (SA = PE1, DA = PE2 End.DT4) → customer IPv4." },
  "l3vpn-p4-decap-repair-only": { doingNow: "P4 removed only the repair outer; the L3VPN outer is intact." },
  "l3vpn-result": { takeaway: "PE2, not P4, executes End.DT4 — the two layers stay independent." },
};
