import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the RSVP-TE FRR lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question steps, so they never state an answer. */
export const FRR_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Keep an RSVP-TE LSP forwarding when a link or router on it fails.", steps: ["intro", "recap", "primary-lsp-up", "predict-r3r5-fail"] },
  { phase: { label: "Normal forwarding", tone: "success" }, objective: "Watch healthy traffic on RSVP-PRIMARY as a baseline.", steps: ["send-normal-1", "r1-push-normal", "r3-swap-normal", "r5-swap-normal", "r7-pop-normal", "r6-deliver-normal"] },
  { phase: { label: "No protection", tone: "danger" }, objective: "See what a failure does when nothing was prepared in advance.", steps: ["no-frr-intro", "fail-no-frr", "r3-no-backup", "normal-recovery-concept", "restore-for-frr"] },
  { phase: { label: "FRR concepts", tone: "violet" }, objective: "Learn the roles: protected resource, PLR, Merge Point, bypass.", steps: ["frr-intro", "terminology-intro", "predict-plr", "plr-explain", "mp-explain", "facility-backup-intro", "distinguish-lsps", "protection-lifecycle-intro"] },
  { phase: { label: "Link protection", tone: "mpls" }, objective: "Pre-signal a bypass around R3-R5 and confirm it carries nothing yet.", steps: ["establish-link-bypass", "bypass-labels", "bypass-bandwidth", "protection-ready-state", "send-normal-2", "r1-push-normal-2", "r3-swap-normal-2"] },
  { phase: { label: "Local repair", tone: "warning" }, objective: "Fail R3-R5 and watch the PLR switch to the bypass on its own.", steps: ["trigger-failure", "detection-note", "r3-detects", "r3-checks-backup", "activate-local-repair"] },
  { phase: { label: "Repair data plane", tone: "mpls" }, objective: "Follow a packet through the bypass and back onto the LSP.", steps: ["send-repaired", "r1-push-repaired", "r3-push-bypass", "r4-transit-bypass", "r5-merge", "r7-pop-repaired", "r6-deliver-repaired"] },
  { phase: { label: "Reoptimization", tone: "violet" }, objective: "See the headend replace the temporary detour with a new end-to-end LSP.", steps: ["views-intro", "reoptimization-intro", "reoptimization-compute", "reoptimization-complete"] },
  { phase: { label: "Node protection", tone: "danger" }, objective: "Find out what a whole-router failure needs from a bypass.", steps: ["node-protection-intro", "why-link-insufficient", "predict-link-protects-node", "reset-for-node-demo", "fail-r5-node", "link-bypass-fails-too", "node-protection-explain", "establish-node-bypass", "node-repair-activate"] },
  { phase: { label: "Node repair data plane", tone: "mpls" }, objective: "Follow a packet around a failed R5 to the new Merge Point.", steps: ["send-node-repaired", "r1-push-node", "r3-push-node-bypass", "r4-transit-node-bypass", "r7-merge-node", "r6-deliver-node", "link-vs-node-table"] },
  { phase: { label: "Advanced", tone: "cyan" }, objective: "Compare backup styles and why facility backup scales.", steps: ["backup-styles-intro", "multiple-lsps-concept"] },
  { phase: { label: "Bypass failure", tone: "warning" }, objective: "Tell a loss of protection apart from a loss of service.", steps: ["bypass-failure-intro", "fail-bypass-link", "protection-unavailable", "restore-bypass-link"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "FRR was reported READY, yet traffic didn't recover. Find the mismatch.", steps: ["troubleshooting-intro", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the fix that restores protection against this failure.", steps: ["repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repaired protection carries real traffic.", steps: ["repaired-activate", "verify-data-packet", "verify-push", "verify-frr", "verify-deliver"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review local repair, link vs node protection, and the repair stack.", steps: ["complete"] },
];

export const FRR_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "primary-lsp-up": { doingNow: "RSVP-PRIMARY: R1 → R3 → R5 → R7 → R6, 500 Mbps, UP." },
  "predict-r3r5-fail": { doingNow: "Think about what was, or wasn't, prepared before the failure." },
  "send-normal-1": { doingNow: "Data plane: a packet is classified into RSVP-PRIMARY." },
  "r1-push-normal": { doingNow: "Data plane: R1 pushes the primary LSP label." },
  "r3-swap-normal": { doingNow: "Data plane: R3 swaps toward R5." },
  "r5-swap-normal": { doingNow: "Data plane: R5 swaps toward R7." },
  "r7-pop-normal": { doingNow: "Data plane: R7 pops (PHP) toward R6." },
  "fail-no-frr": { doingNow: "R3-R5 fails with no bypass anywhere." },
  "r3-no-backup": { takeaway: "No pre-built backup means traffic waits for the headend." },
  "frr-intro": { takeaway: "FRR is local repair prepared in advance, not a faster CSPF." },
  "predict-plr": { doingNow: "Think about which router is attached to the failed resource." },
  "mp-explain": { doingNow: "The Merge Point is where the detour rejoins the primary path." },
  "distinguish-lsps": { takeaway: "Primary = customer path. Bypass = local detour around one resource." },
  "establish-link-bypass": { doingNow: "Control plane: R3 signals a bypass R3 → R4 → R5 that avoids R3-R5." },
  "bypass-labels": { doingNow: "Control plane: R5 advertises implicit-null to R4; R4 advertises the bypass label to R3." },
  "bypass-bandwidth": { doingNow: "Bandwidth is reserved on the bypass, but 0 Mbps flows through it." },
  "protection-ready-state": { takeaway: "Protection READY, yet normal traffic still uses the primary path." },
  "r1-push-normal-2": { doingNow: "R1 has no idea a bypass exists." },
  "trigger-failure": { doingNow: "R3-R5 fails, this time with protection in place." },
  "r3-detects": { doingNow: "R3 detects locally. No CSPF, no message to R1 first." },
  "activate-local-repair": { takeaway: "Pre-signaled means no new signaling at failure time." },
  "send-repaired": { doingNow: "Data plane: R1 still sends exactly as before." },
  "r3-push-bypass": { doingNow: "Data plane: R3 swaps to the label R5 expects, then pushes the bypass label on top.", takeaway: "FRR Repair · Outer: bypass label · Inner: protected LSP label." },
  "r4-transit-bypass": { doingNow: "Data plane: R4 acts on the outer bypass label only and pops it (PHP)." },
  "r5-merge": { doingNow: "Data plane: R5 receives its usual primary label and swaps as normal." },
  "r6-deliver-repaired": { takeaway: "Only the segment around the failure changed." },
  "reoptimization-compute": { doingNow: "Control plane: R1 runs CSPF again, avoiding the failed link." },
  "why-link-insufficient": { doingNow: "Look at where the link bypass ends." },
  "predict-link-protects-node": { doingNow: "Consider what the bypass needs at its far end." },
  "fail-r5-node": { doingNow: "This time the whole R5 router fails." },
  "node-protection-explain": { doingNow: "A node-protecting bypass must avoid R5 entirely and merge at the next hop after it." },
  "establish-node-bypass": { doingNow: "Control plane: R3 signals R3 → R4 → R7, skipping R5." },
  "r3-push-node-bypass": { doingNow: "Data plane: R3 swaps to the label R7 expects, then pushes the node-bypass label.", takeaway: "Inner label = what the Merge Point expects." },
  "r4-transit-node-bypass": { doingNow: "Data plane: R4 pops the outer bypass label only." },
  "r7-merge-node": { doingNow: "Data plane: R7 (Merge Point) receives its usual label and pops (PHP) toward R6." },
  "link-vs-node-table": { takeaway: "Same PLR, different Merge Point, different failures covered." },
  "fail-bypass-link": { doingNow: "R4-R7 fails. It's on the bypass, not on the primary." },
  "protection-unavailable": { takeaway: "Primary UP, protection UNAVAILABLE: a risk, not an outage." },
  "troubleshooting-intro": { doingNow: "Read the incident: what failed, and what was protected?" },
  "diagnostic-ladder": { doingNow: "Compare the protected resource with the failed resource." },
  "repair-challenge": { doingNow: "Fix the mismatch you identified. Wrong choices explain why." },
  "verify-frr": { doingNow: "Data plane: R3 → R4 → R7 carries the repaired detour." },
  "verify-deliver": { takeaway: "The repaired protection survives the failure that defeated the original bypass." },
};
