import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the SR Policy lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. */
export const SRP_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Turn individual SIDs into an operational traffic-engineering policy.", steps: ["intro"] },
  { phase: { label: "Baseline", tone: "ospf" }, objective: "Send traffic with only R6's Node SID — no policy yet.", steps: ["baseline-intro", "baseline-send", "baseline-r1-push", "baseline-r2-continue", "baseline-r4-pop", "baseline-deliver"] },
  { phase: { label: "Policy intent", tone: "violet" }, objective: "Define what the policy is: headend, color and endpoint.", steps: ["sr-policy-intro", "policy-identity", "color-accuracy", "endpoint-explain", "predict-color-label"] },
  { phase: { label: "Candidate paths", tone: "mpls" }, objective: "Build an explicit and a dynamic candidate for the same intent.", steps: ["candidate-paths-intro", "explicit-candidate-intro", "explicit-candidate-validation", "dynamic-candidate-intro", "te-attributes", "dynamic-computation", "dynamic-segment-list"] },
  { phase: { label: "Selection", tone: "warning" }, objective: "Work out which candidate becomes active, and why.", steps: ["candidate-selection-fn", "policy-state-intro", "predict-preference-both-valid", "active-candidate-shown", "segment-list-viewer-intro"] },
  { phase: { label: "BSID", tone: "violet" }, objective: "Bind a local forwarding handle to the policy.", steps: ["bsid-intro", "bsid-binding"] },
  { phase: { label: "Steering", tone: "cyan" }, objective: "Connect the policy to real traffic.", steps: ["predict-up-means-steered", "steering-intro", "steering-method", "flows-intro"] },
  { phase: { label: "Data plane", tone: "mpls" }, objective: "Follow a GOLD packet from classification to delivery.", steps: ["send-gold", "gold-r1-classify", "gold-r1-push", "gold-r3-node-complete", "gold-r3-execute-adj", "gold-r5-continue", "gold-r6-pop", "gold-deliver", "default-vs-gold", "views-intro"] },
  { phase: { label: "Preference", tone: "warning" }, objective: "Change a preference and watch the active candidate respond.", steps: ["preference-experiment-intro", "preference-switch", "preference-restore"] },
  { phase: { label: "Fallback", tone: "danger" }, objective: "Break the explicit path and observe the policy's response.", steps: ["invalidation-intro", "fail-r3-r5", "predict-invalid-vs-valid", "policy-resolving", "dynamic-becomes-active", "predict-fallback-tilfa", "not-tilfa", "restore-r3-r5"] },
  { phase: { label: "No valid candidate", tone: "danger" }, objective: "See what happens to GOLD traffic when no candidate is valid.", steps: ["no-valid-candidate-intro", "fail-both-gold-links", "policy-down", "strict-steering-send", "gold-fails", "default-still-healthy", "restore-all-links"] },
  { phase: { label: "Advanced", tone: "violet" }, objective: "Separate preference from weight, and explore the policy lab.", steps: ["segment-list-weights-note", "preference-vs-weight", "policy-lab-intro", "affinity-experiment"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "GOLD traffic arrives but not on the engineered path. Find out why.", steps: ["troubleshooting-intro", "incident-trace", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores the intended active candidate.", steps: ["repair-challenge"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real GOLD packet.", steps: ["verify-resend", "verify-r1-push", "verify-transit", "verify-deliver"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Build the full GOLD intent with an explicit path and a valid fallback.", steps: ["engineer-challenge"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review identity, candidates, selection, BSID and steering.", steps: ["complete"] },
];

export const SRP_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "baseline-r1-push": { doingNow: "Data plane: R1 pushes 16006 S1 — R6's Node SID, no policy." },
  "baseline-r4-pop": { doingNow: "Data plane: R4 is penultimate for R6 and pops 16006 (PHP)." },
  "baseline-deliver": { takeaway: "Default traffic follows the IGP shortest path R1 → R2 → R4 → R6." },
  "policy-identity": { doingNow: "Control/policy state: headend R1, Color 100, endpoint R6 (10.0.0.6/32)." },
  "color-accuracy": { takeaway: "\"GOLD\" is PacketVerse's name for the intent — it never appears on the wire." },
  "predict-color-label": { doingNow: "Think about what Color identifies." },
  "explicit-candidate-intro": { doingNow: "GOLD-EXPLICIT, preference 200: logical list 16003 → 24035 → 16006." },
  "dynamic-candidate-intro": { doingNow: "GOLD-DYNAMIC, preference 100: computed from TE metric and affinity." },
  "te-attributes": { doingNow: "Top links BLUE; bottom links GOLD; R4-R6 carries both; R3-R4 is GOLD." },
  "dynamic-segment-list": { doingNow: "Computed list: 16005 → 16006 — same physical path, fewer SIDs." },
  "predict-preference-both-valid": { doingNow: "Both candidates are valid — compare what selection looks at." },
  "segment-list-viewer-intro": { takeaway: "The viewer shows the active candidate's logical list, not the wire stack." },
  "bsid-intro": { doingNow: "Control/policy state: R1 allocates BSID 30001 for this policy." },
  "bsid-binding": { takeaway: "Only R1 interprets 30001; transit routers never see it." },
  "predict-up-means-steered": { doingNow: "Separate building a policy from sending traffic into it." },
  "gold-r1-classify": { doingNow: "Policy state: Color 100 → policy ⟨R1, 100, R6⟩ → BSID 30001 → active candidate." },
  "gold-r1-push": { doingNow: "Wire stack R1 → R3: 24035 S0 over 16006 S1 — 16003 completed by PHP at R1.", takeaway: "Logical policy list ≠ wire stack." },
  "gold-r3-node-complete": { doingNow: "No pop at R3; 24035 (R3's local Adj-SID) is on top." },
  "gold-r3-execute-adj": { doingNow: "R3 executes 24035; R3 → R5 carries 16006 S1." },
  "gold-r5-continue": { doingNow: "R5 is penultimate for R6 and pops 16006 (PHP); R5 → R6 is plain IP." },
  "gold-r6-pop": { takeaway: "R6 receives plain IP — it never pops 16006 itself." },
  "gold-deliver": { takeaway: "GOLD follows R1 → R3 → R5 → R6; transit routers never saw Color, preference or BSID." },
  "preference-switch": { doingNow: "Policy state: GOLD-EXPLICIT preference 200 → 50." },
  "fail-r3-r5": { doingNow: "Topology: R3-R5 is down, so the explicit list's Adj-SID is unusable." },
  "predict-invalid-vs-valid": { doingNow: "Recall which candidates selection is allowed to consider." },
  "dynamic-becomes-active": { doingNow: "GOLD-DYNAMIC recomputes to R1 → R3 → R4 → R6 over the GOLD-tagged R3-R4 link." },
  "predict-fallback-tilfa": { doingNow: "Consider where and when each mechanism acts." },
  "policy-down": { doingNow: "Policy state: no valid candidate — Color 100 is DOWN." },
  "gold-fails": { takeaway: "Strict steering: GOLD is not silently sent over the IGP path." },
  "default-still-healthy": { takeaway: "Reachability and policy intent are separate concerns." },
  "troubleshooting-intro": { doingNow: "GOLD reaches R6 with no loss, yet not over the expected path." },
  "incident-trace": { doingNow: "Compare the traced path with the candidate operations expected." },
  "diagnostic-ladder": { doingNow: "Healthy connectivity, wrong intent — look at selection inputs." },
  "repair-challenge": { doingNow: "Pick the change that makes the intended candidate win selection again." },
  "verify-r1-push": { doingNow: "Wire stack R1 → R3: 24035 S0 over 16006 S1." },
  "verify-transit": { doingNow: "R3 executes 24035; R5 pops 16006 (PHP). The Inspector shows the last stage: R5 → R6, plain IP." },
  "verify-deliver": { takeaway: "Repair verified over R1 → R3 → R5 → R6." },
};
