import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for SRv6 Policy — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/repair steps, so they never state an answer. */
export const SRV6P_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Turn a network intent into SRv6 forwarding state.", steps: ["intro", "ordinary-vs-te", "sr-policy-intro"] },
  { phase: { label: "Policy intent", tone: "violet" }, objective: "Define the policy: headend, color and endpoint.", steps: ["policy-identity", "color-accuracy", "predict-color-srv6-sid", "sr-mpls-vs-srv6-model"] },
  { phase: { label: "Topology", tone: "ospf" }, objective: "Compare the IGP metric with the delay metric on both paths.", steps: ["topology-intro", "predict-igp-shortest", "delay-metric-reveal"] },
  { phase: { label: "SIDs", tone: "ip" }, objective: "Pick the SIDs the policy's segment lists will use.", steps: ["sid-allocation", "why-dx6-not-end", "why-not-r3-end-first"] },
  { phase: { label: "Candidate paths", tone: "mpls" }, objective: "Build an explicit and a dynamic candidate for the same intent.", steps: ["explicit-candidate-intro", "explicit-forwarding-preview", "explicit-candidate-validation", "dynamic-candidate-intro", "dynamic-computation-explain", "dynamic-segment-list-reveal", "predict-dynamic-recompute"] },
  { phase: { label: "Selection", tone: "warning" }, objective: "Work out which candidate becomes active, and why.", steps: ["selection-fn-explain", "predict-both-valid-preference", "active-candidate-shown"] },
  { phase: { label: "BSID", tone: "violet" }, objective: "Bind a local forwarding handle to the policy.", steps: ["bsid-intro", "predict-bsid-mpls"] },
  { phase: { label: "Steering", tone: "cyan" }, objective: "Connect the policy to real traffic.", steps: ["steering-separate", "predict-up-means-steered", "steering-method", "color-not-srh-field", "h-encaps-explain"] },
  { phase: { label: "Data plane", tone: "ip" }, objective: "Follow a LOW_LATENCY probe from H.Encaps to R6's decapsulation.", steps: ["send-low-latency", "r1-steering-match", "r1-policy-select", "r1-h-encaps", "predict-hencaps-da", "r1-forward-to-r3", "r3-local-sid-match", "r3-execute-endx", "r3-forward-adjacency", "r5-transit", "r6-execute-dx6", "r6-deliver", "full-srh-recap", "hencaps-red-preview"] },
  { phase: { label: "Weighted lists", tone: "violet" }, objective: "Split flows across weighted segment lists.", steps: ["weighted-lab-intro", "weighted-lab-explain", "candidate-not-segment-list"] },
  { phase: { label: "Failover", tone: "danger" }, objective: "Break the explicit path and observe the policy's response.", steps: ["failure-intro", "fail-r3-r5", "predict-invalid-vs-valid", "dynamic-recompute", "dynamic-becomes-active", "predict-candidate-vs-policy-failure", "send-after-failover", "failover-h-encaps", "failover-transit", "not-tilfa"] },
  { phase: { label: "Fault", tone: "danger" }, objective: "The link is back, yet the preferred candidate stays inactive. Find out why.", steps: ["restore-r3-r5-partial", "incident-report", "predict-fault-hypothesis", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that addresses the cause you isolated.", steps: ["repair-challenge", "repair-verified-note"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real packet, then review the wrong fixes.", steps: ["mandatory-resend", "repaired-h-encaps", "repaired-transit", "wrong-repair-1-note", "wrong-repair-2-note", "wrong-repair-3-note"] },
  { phase: { label: "No valid candidate", tone: "danger" }, objective: "See what happens to steered traffic when no candidate is valid.", steps: ["policy-invalid-setup", "policy-invalid-shown", "predict-drop-mandatory", "default-fallback-demo", "enable-drop-upon-invalid", "drop-upon-invalid-demo", "restore-topology-final"] },
  { phase: { label: "BSID in action", tone: "violet" }, objective: "Compare H.Encaps with End.B6.Encaps, and compare with SR-MPLS.", steps: ["hencaps-vs-bsid-intro", "bsid-experiment-setup", "bsid-experiment-execute", "b6-encaps-red-preview", "sr-mpls-comparison"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review identity, candidates, selection, steering and H.Encaps.", steps: ["engineer-challenge-complete", "complete"] },
];

export const SRV6P_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "policy-identity": { doingNow: "Policy state: headend R1, Color 100, endpoint R6." },
  "delay-metric-reveal": { doingNow: "TOP delay 60, BOTTOM delay 15 — the IGP and delay winners differ." },
  "sid-allocation": { doingNow: "R3 End and End.X → R5; R5 End; R6 End.DX6 → RECEIVER6." },
  "explicit-candidate-intro": { doingNow: "CP-EXPLICIT, preference 200: ⟨R3 End.X, R6 End.DX6⟩." },
  "dynamic-candidate-intro": { doingNow: "CP-DYNAMIC, preference 100, objective MIN_DELAY." },
  "dynamic-segment-list-reveal": { doingNow: "Derived list ⟨R5 End, R6 End.DX6⟩ — R1's shortest path to R5 already passes R3." },
  "bsid-intro": { doingNow: "Policy state: R1 allocates a Binding SID 2001:db8:100:1:9000:: for this policy." },
  "color-not-srh-field": { takeaway: "Color 100 selects the policy; it never appears on the wire." },
  "send-low-latency": { doingNow: "CLIENT1's original IPv6 probe — no SRv6 header yet." },
  "r1-steering-match": { doingNow: "Policy state: LOW_LATENCY → Color 100 → policy ⟨R1, 100, R6⟩." },
  "r1-policy-select": { doingNow: "CP-EXPLICIT is valid and has the highest preference — its list is imposed." },
  "r1-h-encaps": { doingNow: "H.Encaps: outer DA = R3 End.X; SRH SL 1 / LE 1 with [0] R6 End.DX6 · [1] R3 End.X; inner probe preserved." },
  "r1-forward-to-r3": { doingNow: "Ordinary FIB lookup toward R3's locator — directly connected." },
  "r3-local-sid-match": { doingNow: "R3's Local SID Table matches its End.X SID (adjacency R5)." },
  "r3-execute-endx": { doingNow: "End.X at R3: SL 1 → 0, DA ← R6 End.DX6 — the DA is not R5's address." },
  "r3-forward-adjacency": { doingNow: "Forced out the bound adjacency R3 → R5." },
  "r5-transit": { doingNow: "R5 is transit: the DA is R6's SID." },
  "r6-execute-dx6": { doingNow: "R6 matches End.DX6 with SL 0 — the final segment." },
  "r6-deliver": { doingNow: "Shown: the packet at R6 before End.DX6 decap; the inner probe goes to RECEIVER6.", takeaway: "Path R1 → R3 → R5 → R6: the policy, not the IGP TOP path." },
  "fail-r3-r5": { doingNow: "Topology: R3-R5 down → R1's SR Database drops verification of R3's End.X SID." },
  "dynamic-recompute": { doingNow: "CP-DYNAMIC recomputes over R1 → R3 → R4 → R6 (delay 40)." },
  "dynamic-becomes-active": { doingNow: "Policy state: the policy stays UP with CP-DYNAMIC active." },
  "failover-h-encaps": { doingNow: "Fresh H.Encaps from CP-DYNAMIC: outer DA = R3 End SID." },
  "failover-transit": { doingNow: "Shown: after R3 End (DA → R6 End.DX6, SL 0), before R6's decap." },
  "not-tilfa": { takeaway: "Headend re-selection, not local precomputed repair." },
  "restore-r3-r5-partial": { doingNow: "Topology: R3-R5 is up and R3 still has its End.X SID installed." },
  "incident-report": { doingNow: "Link up, SID installed, IPv6 healthy — yet CP-DYNAMIC is still active." },
  "repair-challenge": { doingNow: "Choose the fix that addresses the cause the ladder isolated." },
  "repaired-h-encaps": { doingNow: "CP-EXPLICIT is active again: outer DA = R3 End.X." },
  "repaired-transit": { doingNow: "Shown: after R3 End.X via R3 → R5, before R6 End.DX6 decap.", takeaway: "Repair verified with a real resend." },
  "policy-invalid-shown": { doingNow: "Policy state: no valid candidate — NO_VALID_CANDIDATE." },
  "default-fallback-demo": { doingNow: "Drop-Upon-Invalid OFF: PacketVerse's modeled fallback to IGP forwarding." },
  "drop-upon-invalid-demo": { doingNow: "Drop-Upon-Invalid ON: steering stays attached and the action is DROP." },
  "bsid-experiment-execute": { doingNow: "End.B6.Encaps: the incoming SRH advances, then a new outer IPv6 + SRH is pushed (DA = R3 End.X)." },
};
