import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the BGP-signaled VPLS lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/challenge steps, so they never state an answer. */
export const BGP_VPLS_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Replace targeted-LDP signaling for CUST-A-VPLS with BGP, and find out exactly what changes.", steps: ["intro", "recap-ldp-vpls", "predict-can-bgp-signal", "bgp-vpls-mental-model", "topology-intro"] },
  { phase: { label: "BGP session", tone: "bgp" }, objective: "Bring up MP-BGP from every PE to RR1 and enable the right address family.", steps: ["bgp-control-topology-intro", "transport-recap-intro", "transport-lsp-up", "mp-bgp-sessions-up", "predict-transport-independent", "predict-transport-vs-membership", "afi-safi-intro", "enable-l2vpn-vpls-af"] },
  { phase: { label: "VE information", tone: "violet" }, objective: "Learn the identifiers each PE puts into its advertisement.", steps: ["rd-intro", "rt-intro", "predict-rt-purpose", "ve-id-intro"] },
  { phase: { label: "Label block", tone: "mpls" }, objective: "Understand what a label block advertises and how labels come out of it.", steps: ["label-block-intro", "nlri-anatomy", "layer2-info-intro", "predict-label-base-not-final-label"] },
  { phase: { label: "Auto-discovery", tone: "bgp" }, objective: "Advertise, reflect, receive and import each PE's VPLS NLRI.", steps: ["pe1-advertises", "rr1-reflects", "pe2-receives", "pe2-rt-import-check", "pe2-discovers-pe1", "pe3-receives-imports", "pe2-advertises", "pe3-advertises", "full-mesh-membership-recap", "predict-rr-not-dataplane"] },
  { phase: { label: "PW establishment", tone: "mpls" }, objective: "Derive every directional PW label from the imported label blocks.", steps: ["label-block-viewer-pe1", "predict-receive-side-meaning", "compute-pe1-to-pe2", "compute-pe2-to-pe1", "compute-pe1-to-pe3", "compute-pe3-to-pe1", "compute-pe2-to-pe3", "compute-pe3-to-pe2", "six-labels-recap", "pw-mesh-up", "bgp-table-no-macs", "fdb-empty-recap"] },
  { phase: { label: "MAC learning & BUM", tone: "warning" }, objective: "Send the first frame over the BGP-signaled mesh and see how PEs find CE2.", steps: ["send-ce1-to-ce2-1", "pe1-learn-ce1", "pe1-lookup-ce2-unknown", "predict-unknown-unicast-bgp", "pe1-flood-decision", "flood-copy-visual", "pe1-push-copy-pe2", "core-forward-to-pe2", "pe2-pw-lookup-learn-ce1", "pe2-deliver-ce2", "pe3-parallel-copy", "split-horizon-intro", "split-horizon-visual"] },
  { phase: { label: "Known unicast", tone: "success" }, objective: "Send the reply and see how far BGP is involved in forwarding it.", steps: ["ce2-sends-to-ce1", "pe2-learn-ce2-local", "pe2-direct-to-pe1", "pe1-learn-ce2-remote", "known-unicast-recap", "predict-bgp-doesnt-carry-macs"] },
  { phase: { label: "Comparisons", tone: "violet" }, objective: "Place BGP-VPLS between LDP-VPLS and EVPN.", steps: ["ldp-vpls-vs-bgp-vpls", "bgp-vpls-vs-evpn", "why-evpn-developed-note", "predict-switching-doesnt-remove-learning", "control-data-both-recap"] },
  { phase: { label: "Label-block edge case", tone: "warning" }, objective: "See what happens when a VE ID falls outside the advertised blocks.", steps: ["label-block-expansion-intro", "pe3-ve-id-change-to-7", "predict-out-of-block", "out-of-block-symptom", "expand-block-pe1", "expand-block-pe2", "label-block-lesson", "veid-reset-rejoin"] },
  { phase: { label: "Withdrawal", tone: "danger" }, objective: "Remove and re-add a PE through BGP alone.", steps: ["withdrawal-intro", "pe3-withdraws", "pe3-rejoins"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "PE3's session is Established but CE3 can't join the service. Find why.", steps: ["troubleshooting-intro", "fault-injection", "incident-symptoms", "predict-established-doesnt-mean-works", "received-vs-imported-evidence", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores CE3's membership.", steps: ["repair-challenge", "repaired-recompute"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real CE1 → CE3 frame.", steps: ["verify-send-ce1-ce3", "verify-flood-deliver", "verify-known-unicast-after-learning"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Confirm every piece of the BGP-signaled service you built.", steps: ["engineer-challenge-intro", "engineer-challenge-confirm"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review what BGP took over from targeted LDP, and what it didn't.", steps: ["complete"] },
];

export const BGP_VPLS_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "bgp-control-topology-intro": { doingNow: "PE1, PE2 and PE3 each peer only with RR1 in AS 65000." },
  "mp-bgp-sessions-up": { doingNow: "Control plane: three PE ↔ RR1 sessions reach Established." },
  "predict-transport-vs-membership": { doingNow: "Separate session state from service membership." },
  "enable-l2vpn-vpls-af": { doingNow: "Control plane: AFI 25 / SAFI 65 (L2VPN/VPLS) enabled on every session." },
  "rd-intro": { doingNow: "RDs: PE1 65000:1, PE2 65000:2, PE3 65000:3." },
  "predict-rt-purpose": { doingNow: "Compare what the RD does with what the RT does." },
  "ve-id-intro": { doingNow: "VE IDs: PE1 = 1, PE2 = 2, PE3 = 3." },
  "nlri-anatomy": { doingNow: "PE1's NLRI: RD 65000:1, VE 1, VBO 1, VBS 4, Label Base 24000, RT 65000:100." },
  "predict-label-base-not-final-label": { doingNow: "Re-read how a block is described before answering." },
  "pe1-advertises": { doingNow: "Control plane: BGP UPDATE PE1 → RR1 with PE1's VPLS NLRI." },
  "rr1-reflects": { doingNow: "Control plane: RR1 reflects the NLRI to PE2 and PE3." },
  "pe2-rt-import-check": { doingNow: "PE2 compares the RT 65000:100 with its own import RT." },
  "pe2-discovers-pe1": { takeaway: "Received + RT match = imported = discovered." },
  "predict-rr-not-dataplane": { doingNow: "Think about where RR1 sits in the physical data path." },
  "predict-receive-side-meaning": { doingNow: "Think about what a label from PE1's own block tells PE1." },
  "compute-pe1-to-pe2": { doingNow: "PE1 → PE2 = PE2's base 25000 + PE1's VE 1 − VBO 1 = 25000." },
  "compute-pe2-to-pe1": { doingNow: "PE2 → PE1 = PE1's base 24000 + PE2's VE 2 − 1 = 24001." },
  "six-labels-recap": { takeaway: "Label = receiver's Label Base + sender's VE ID − VBO." },
  "bgp-table-no-macs": { takeaway: "BGP carries membership and labels — not customer MACs." },
  "send-ce1-to-ce2-1": { doingNow: "Data plane: CE1 (00:11:11:11:11:11) → CE2 (00:22:22:22:22:22)." },
  "predict-unknown-unicast-bgp": { doingNow: "Recall what the BGP table does and doesn't contain." },
  "pe1-push-copy-pe2": { doingNow: "Data plane: toward PE2 the stack is transport 102 (S0) over BGP-derived 25000 (S1)." },
  "split-horizon-visual": { takeaway: "Same mesh split horizon as LDP-VPLS: signaling changed, bridging didn't." },
  "pe2-direct-to-pe1": { doingNow: "Data plane: one copy, transport 201 (S0) over BGP-derived 24001 (S1)." },
  "predict-bgp-doesnt-carry-macs": { doingNow: "Look back at the BGP table check." },
  "predict-switching-doesnt-remove-learning": { doingNow: "Compare the data-plane steps in both lessons." },
  "pe3-ve-id-change-to-7": { doingNow: "PE3 re-advertises with VE ID 7; PE1/PE2 blocks still cover 1–4." },
  "predict-out-of-block": { doingNow: "Think about what the label formula needs from the block." },
  "expand-block-pe1": { doingNow: "Control plane: PE1 widens its block to VBS 8, same base 24000." },
  "pe3-withdraws": { doingNow: "Control plane: BGP WITHDRAW of PE3's VPLS NLRI." },
  "fault-injection": { doingNow: "PE3's service policy changed; its BGP session stays Established." },
  "received-vs-imported-evidence": { doingNow: "Compare what each PE RECEIVED with what it IMPORTED." },
  "diagnostic-ladder": { doingNow: "Walk up: interfaces, IGP, transport, BGP sessions, address family, then policy." },
  "repair-challenge": { doingNow: "Pick the repair that fixes the layer you identified. Wrong choices explain why." },
  "verify-flood-deliver": { doingNow: "Data plane: PE1 floods to PE2 and PE3 again — the PE1–PE3 PW is back." },
};
