import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the traditional VPLS lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question/challenge steps, so they never state an answer. */
export const VPLS_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "Give CE1, CE2 and CE3 one shared Ethernet LAN across the provider.", steps: ["intro", "recap-vpws", "multipoint-question", "vpls-mental-model", "topology-intro"] },
  { phase: { label: "Service membership", tone: "violet" }, objective: "Define the VPLS service and each PE's bridge context.", steps: ["vpls-service-instance", "vpls-bridge-context", "bridge-ports-intro"] },
  { phase: { label: "Transport", tone: "mpls" }, objective: "Confirm label-switched paths between every PE loopback.", steps: ["transport-recap-intro", "transport-lsp-up"] },
  { phase: { label: "PW mesh", tone: "violet" }, objective: "Bring up the pseudowires between the PEs and inspect their labels.", steps: ["targeted-ldp-intro", "targeted-ldp-operational", "why-full-mesh-question", "pw-id-vs-vpls-identity", "establish-pw-pe1-pe2", "establish-pw-pe1-pe3", "establish-pw-pe2-pe3", "full-mesh-visual", "initial-state-recap", "predict-p-router-vpls"] },
  { phase: { label: "MAC learning", tone: "success" }, objective: "Send the first frame and watch what each PE learns from it.", steps: ["mac-learning-intro", "send-ce1-to-ce2-1", "pe1-learn-ce1", "pe1-lookup-ce2-unknown"] },
  { phase: { label: "Unknown unicast", tone: "warning" }, objective: "Decide what PE1 does with a frame for a MAC it has never seen, then follow every copy.", steps: ["predict-unknown-unicast", "pe1-flood-decision", "flood-copy-visual", "pe1-push-copy-pe2", "core-forward-to-pe2", "pe2-pw-lookup-learn-ce1", "pe2-deliver-ce2", "pe3-parallel-copy"] },
  { phase: { label: "Split horizon", tone: "danger" }, objective: "Examine the forwarding rule for frames that arrive on a pseudowire.", steps: ["split-horizon-intro", "split-horizon-visual", "why-full-mesh-answer", "predict-pw-to-pw-relay", "split-horizon-terminology"] },
  { phase: { label: "BUM", tone: "warning" }, objective: "See how broadcast and multicast are handled compared with unknown unicast.", steps: ["broadcast-intro", "ce1-arp-broadcast", "pe1-flood-broadcast", "bum-comparison-panel"] },
  { phase: { label: "Known unicast", tone: "success" }, objective: "Use what was learned to send single, direct copies.", steps: ["ce2-response-intro", "ce2-sends-to-ce1", "pe2-learn-ce2-local", "pe2-direct-to-pe1", "pe1-learn-ce2-remote", "signature-mac-learning-sequence", "send-ce1-to-ce2-2-known", "pe1-known-unicast-direct", "mac-table-per-pe", "data-plane-vs-control-plane"] },
  { phase: { label: "Aging & moves", tone: "cyan" }, objective: "Watch FDB entries age out, get relearned and move.", steps: ["mac-aging-intro", "age-ce2-entry", "send-after-aging-unknown-again", "relearn-after-flood", "mac-move-intro", "move-ce2-to-pe3", "mac-move-demonstrate", "mac-move-recap", "mac-withdrawal-note", "predict-remote-learn", "predict-aging-behavior"] },
  { phase: { label: "Comparisons", tone: "violet" }, objective: "Place traditional VPLS between VPWS and EVPN.", steps: ["vpls-vs-vpws-comparison", "vpls-vs-evpn-comparison", "why-evpn-developed"] },
  { phase: { label: "Failure", tone: "danger" }, objective: "CE1 can't reach CE3 while every other pair works. Find out why.", steps: ["troubleshooting-intro", "fault-injection", "incident-symptoms", "diagnostic-ladder", "demonstrate-fault", "signature-fault-visual"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Apply the one fix that restores CE1 ↔ CE3.", steps: ["repair-challenge", "repaired-recompute"] },
  { phase: { label: "Verify", tone: "success" }, objective: "Prove the repair with a real CE1 → CE3 frame.", steps: ["verify-send-ce1-ce3", "verify-push-deliver", "verify-known-unicast-after-learning"] },
  { phase: { label: "Challenge", tone: "violet" }, objective: "Confirm every piece of the virtual LAN you built.", steps: ["engineer-challenge-intro", "engineer-challenge-confirm"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review mesh, learning, flooding and split horizon.", steps: ["complete"] },
];

export const VPLS_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  "topology-intro": { doingNow: "CE1/CE2/CE3 hang off PE1/PE2/PE3; P1–P3 are transport only." },
  "vpls-service-instance": { doingNow: "Every PE configures CUST-A-VPLS, service identity VPLS-500." },
  "bridge-ports-intro": { takeaway: "Each PE's bridge has one AC port and one PW port per remote PE." },
  "targeted-ldp-operational": { doingNow: "Control plane: targeted LDP is up mesh-wide." },
  "why-full-mesh-question": { doingNow: "Think about how many PE pairs exist and what each needs." },
  "establish-pw-pe1-pe2": { doingNow: "Control plane: PE1 receives on 24012 from PE2; PE2 receives on 25021 from PE1." },
  "establish-pw-pe1-pe3": { doingNow: "Control plane: PE1 receives on 24013 from PE3; PE3 receives on 26031 from PE1." },
  "establish-pw-pe2-pe3": { doingNow: "Control plane: PE2 receives on 25023 from PE3; PE3 receives on 26032 from PE2." },
  "initial-state-recap": { takeaway: "The bridge exists, but every FDB is empty." },
  "predict-p-router-vpls": { doingNow: "Recall what P routers did in VPWS." },
  "send-ce1-to-ce2-1": { doingNow: "Data plane: CE1 (00:11:11:11:11:11) → CE2 (00:22:22:22:22:22)." },
  "pe1-learn-ce1": { doingNow: "Data plane: PE1 learns CE1's MAC on AC: CE1." },
  "predict-unknown-unicast": { doingNow: "Think about which ports could possibly lead to CE2." },
  "flood-copy-visual": { doingNow: "Data plane: two replicas leave PE1, each with its own label stack." },
  "pe1-push-copy-pe2": { doingNow: "Data plane: toward PE2 the stack is transport 102 (S0) over PE2's PW label 25021 (S1)." },
  "pe2-pw-lookup-learn-ce1": { doingNow: "Data plane: PE2 learns CE1 → PW: PE1 from the frame itself." },
  "pe2-deliver-ce2": { takeaway: "Remote MACs are learned by watching frames arrive on PWs." },
  "split-horizon-visual": { takeaway: "Classic VPLS: frames received on a mesh PW never leave on another mesh PW." },
  "predict-pw-to-pw-relay": { doingNow: "Consider what would happen if PEs relayed between PWs in a full mesh." },
  "ce1-arp-broadcast": { doingNow: "Data plane: CE1 broadcasts to ff:ff:ff:ff:ff:ff." },
  "bum-comparison-panel": { takeaway: "Broadcast, unknown unicast and multicast share the replicate-except-ingress treatment." },
  "pe2-direct-to-pe1": { doingNow: "Data plane: one copy only: transport 201 (S0) over PE1's PW label 24012 (S1)." },
  "pe1-known-unicast-direct": { doingNow: "Data plane: PE1 knows CE2 → PW: PE2, so exactly one copy; PE3 gets nothing." },
  "data-plane-vs-control-plane": { takeaway: "Every MAC entry came from observed traffic, never from a control-plane advertisement." },
  "age-ce2-entry": { doingNow: "PE1 removes 00:22:22:22:22:22 from its FDB (aging)." },
  "predict-remote-learn": { doingNow: "Think back to how PE2 learned CE1." },
  "predict-aging-behavior": { doingNow: "Recall what PE1 did the very first time." },
  "fault-injection": { doingNow: "One mesh pseudowire has failed. Transport, targeted LDP and ACs stay up." },
  "diagnostic-ladder": { doingNow: "Check each mesh leg individually, not just the mesh as a whole." },
  "signature-fault-visual": { doingNow: "Data plane: watch which egress ports PE2 is allowed to use." },
  "repair-challenge": { doingNow: "Pick the repair that fixes the cause you identified. Wrong choices explain why." },
  "verify-push-deliver": { doingNow: "Data plane: PE1 floods to both PEs again; toward PE3 the stack is 103 (S0) / 26031 (S1)." },
};
