import type { BriefingPhaseDef, BriefingStepNote } from "@/components/lesson/briefing";

/** Mission Briefing framing for the RSVP-TE lesson — presentation only; the scenario's label/narrative stay the source of truth. Phase objectives also show on question steps, so they never state an answer. */
export const RSVP_TE_BRIEFING_PHASES: BriefingPhaseDef[] = [
  { phase: { label: "Mission", tone: "cyan" }, objective: "See which path R1 uses to reach R6 before any tunnel exists.", steps: ["intro", "topology-intro", "igp-values", "predict-igp-path"] },
  { phase: { label: "IGP baseline", tone: "ospf" }, objective: "Send a plain IP flow and watch ordinary shortest-path forwarding.", steps: ["igp-send", "igp-hop-2", "igp-hop-3"] },
  { phase: { label: "Requirement", tone: "warning" }, objective: "Decide whether the IGP path can carry a 500 Mbps reservation.", steps: ["business-requirement", "predict-should-use-shortest"] },
  { phase: { label: "TE concepts", tone: "violet" }, objective: "Learn what the TE database holds and how CSPF differs from SPF.", steps: ["te-intro", "te-db-intro", "te-source-intro", "cspf-intro", "predict-cspf"] },
  { phase: { label: "CSPF", tone: "violet" }, objective: "Run CSPF for the 500 Mbps request and see which path survives.", steps: ["cspf-analysis-full", "cspf-analysis-evaluate", "cspf-analysis-prune", "cspf-result", "predict-cspf-result", "ero-intro"] },
  { phase: { label: "Signaling: PATH", tone: "mpls" }, objective: "Signal the computed path hop by hop along the ERO.", steps: ["rsvp-signaling-intro", "path-hop-1", "path-r3-pipeline", "path-hop-2", "path-hop-3", "path-tailend"] },
  { phase: { label: "Signaling: RESV", tone: "mpls" }, objective: "Finish signaling: reserve bandwidth and install labels on every hop.", steps: ["predict-resv-direction", "resv-hop-1", "resv-r5-pipeline", "resv-hop-2", "resv-hop-3", "lsp-up", "lsp-lifecycle-intro", "session-tables-intro"] },
  { phase: { label: "Data plane", tone: "success" }, objective: "Send real traffic through the LSP using only installed label state.", steps: ["dataplane-intro", "send-data-packet", "r1-ingress-push", "r3-transit-swap", "r5-egress-pop", "r6-deliver"] },
  { phase: { label: "Explore", tone: "cyan" }, objective: "Compare IGP and TE paths and try other constraints in the CSPF Lab.", steps: ["views-intro", "igp-vs-te-comparison", "interactive-lab-intro", "affinity-intro", "explicit-path-intro", "rro-reveal", "soft-state-intro"] },
  { phase: { label: "Troubleshooting", tone: "danger" }, objective: "A 700 Mbps request finds no path. Work out why.", steps: ["break-intro", "fault-injected", "cspf-fails", "diagnostic-ladder"] },
  { phase: { label: "Repair", tone: "warning" }, objective: "Choose the fix that makes a 700 Mbps LSP feasible.", steps: ["repair-challenge"] },
  { phase: { label: "Re-signal & verify", tone: "success" }, objective: "Re-run CSPF, re-signal PATH/RESV, and prove it with traffic.", steps: ["cspf-recompute-after-repair", "resignal-path", "resignal-resv", "lsp-up-again", "verify-data-packet", "verify-push", "verify-swap", "verify-pop"] },
  { phase: { label: "Complete", tone: "success" }, objective: "Review how constraints, signaling and forwarding fit together.", steps: ["complete"] },
];

export const RSVP_TE_BRIEFING_NOTES: Partial<Record<string, BriefingStepNote>> = {
  intro: { doingNow: "Two paths connect R1 and R6. No tunnel exists yet." },
  "topology-intro": { doingNow: "R1 is the headend (ingress), R6 the tailend (egress)." },
  "igp-values": { doingNow: "Compare the per-link costs on the top and bottom paths." },
  "predict-igp-path": { doingNow: "Plain SPF uses one criterion. Apply it to both paths." },
  "igp-send": { doingNow: "Data plane: a plain IP packet, forwarded by ordinary IGP routing." },
  "igp-hop-3": { takeaway: "Without TE, traffic follows the IGP shortest path." },
  "business-requirement": { doingNow: "The tunnel needs 500 Mbps. Check R2-R4's maximum reservable bandwidth." },
  "predict-should-use-shortest": { doingNow: "Compare the requested bandwidth with R2-R4's ceiling." },
  "te-intro": { doingNow: "TE asks which path satisfies the constraints, not which path is shortest." },
  "te-db-intro": { doingNow: "Open the TE Database panel and read R2-R4's row." },
  "te-source-intro": { doingNow: "IGP TE extensions (OSPF or IS-IS) populate the TED." },
  "predict-cspf": { doingNow: "Recall the two stages described in the CSPF step." },
  "cspf-analysis-evaluate": { doingNow: "Every link is tested against the 500 Mbps constraint." },
  "cspf-analysis-prune": { doingNow: "Failing links are removed before any path is computed." },
  "predict-cspf-result": { doingNow: "Look at what's left of the graph after pruning." },
  "ero-intro": { doingNow: "The ERO lists the hops after R1.", takeaway: "The ERO describes the path; it never forwards data." },
  "rsvp-signaling-intro": { doingNow: "Control plane: PATH and RESV signaling starts. No customer data is involved." },
  "path-hop-1": { doingNow: "Control plane: PATH leaves the headend carrying the ERO and the bandwidth request." },
  "path-r3-pipeline": { doingNow: "R3 records the previous hop and forwards PATH. No label is allocated yet." },
  "path-hop-2": { doingNow: "Control plane: PATH continues downstream along the ERO." },
  "path-hop-3": { doingNow: "Control plane: PATH reaches the tailend." },
  "path-tailend": { doingNow: "R6 checks the request and prepares a reservation response." },
  "predict-resv-direction": { doingNow: "Think about who allocates labels and who needs to learn them." },
  "resv-hop-1": { doingNow: "Control plane: R6 advertises implicit-null (PHP) and reserves 500 Mbps on R5-R6." },
  "resv-r5-pipeline": { doingNow: "R5 installs forwarding state while propagating RESV." },
  "resv-hop-2": { doingNow: "Control plane: R5 advertises label 300 and reserves on R3-R5." },
  "resv-hop-3": { doingNow: "Control plane: R3 advertises label 200 and reserves on R1-R3.", takeaway: "PATH went downstream; RESV came back upstream with labels." },
  "lsp-up": { takeaway: "Every hop admitted the bandwidth and installed labels: LSP UP." },
  "dataplane-intro": { doingNow: "Data packets don't run CSPF or RSVP; they use installed state." },
  "send-data-packet": { doingNow: "Data plane: a packet is classified into the tunnel at R1." },
  "r1-ingress-push": { doingNow: "Data plane: R1 pushes 200." },
  "r3-transit-swap": { doingNow: "Data plane: R3 swaps 200 → 300." },
  "r5-egress-pop": { doingNow: "Data plane: R5 pops (PHP) because R6 signaled implicit-null." },
  "r6-deliver": { takeaway: "Traffic followed the TE path, not the IGP shortest path." },
  "igp-vs-te-comparison": { takeaway: "TE path: higher metric, but guaranteed bandwidth." },
  "interactive-lab-intro": { doingNow: "Try different bandwidths in the CSPF Lab panel." },
  "affinity-intro": { doingNow: "Try an affinity constraint in the CSPF Lab." },
  "rro-reveal": { takeaway: "ERO = requested path. RRO = recorded path." },
  "fault-injected": { doingNow: "The request grows to 700 Mbps; another tunnel already reserves bandwidth on R3-R5." },
  "cspf-fails": { doingNow: "Compare the bottleneck on each path with 700 Mbps. No PATH is sent without a path." },
  "diagnostic-ladder": { doingNow: "Compare required vs available bandwidth link by link in the TE Database." },
  "repair-challenge": { doingNow: "Fix the constraint you identified. Wrong choices explain why." },
  "resignal-path": { doingNow: "Control plane: PATH re-signaled headend → tailend for 700 Mbps." },
  "resignal-resv": { doingNow: "Control plane: RESV returns tailend → headend, re-installing labels." },
  "verify-data-packet": { doingNow: "Data plane: a fresh packet tests the repaired LSP." },
  "verify-pop": { takeaway: "The repaired 700 Mbps LSP carries real traffic end to end." },
};
